const defs=[
['chain','Chain','ch'],['slip','Slip Stitch','sl st'],['single','Single Crochet','sc'],['half','Half Double','hdc'],['double','Double Crochet','dc'],['treble','Treble Crochet','tr'],['dtr','Double Treble','dtr'],['picot','Picot','picot'],['puff','Puff Stitch','puff'],['cluster','Cluster','cl'],['shell','Shell','shell'],['ring','Magic Ring','MR']
].map(([id,name,abbr])=>({id,name,abbr}));
const board=document.getElementById('board'), stitchesEl=document.getElementById('stitches');
let active='chain',items=[],selected=null,history=[],future=[];
function svgFor(type,size,color){const s=size,sw=Math.max(1.7,size/20);let b='';const l=(a,b,c,d)=>`<line x1="${a}" y1="${b}" x2="${c}" y2="${d}"/>`;
if(type==='chain')b=`<ellipse cx="${s/2}" cy="${s/2}" rx="${s*.34}" ry="${s*.14}"/>`;
if(type==='slip')b=`<circle cx="${s/2}" cy="${s/2}" r="${s*.1}" fill="${color}"/>`;
if(type==='single')b=l(s*.25,s*.25,s*.75,s*.75)+l(s*.75,s*.25,s*.25,s*.75);
if(type==='half')b=l(s*.5,s*.1,s*.5,s*.9)+l(s*.27,s*.35,s*.73,s*.35);
if(type==='double')b=l(s*.5,s*.08,s*.5,s*.92)+l(s*.27,s*.30,s*.73,s*.30)+l(s*.30,s*.55,s*.70,s*.40);
if(type==='treble')b=l(s*.5,s*.05,s*.5,s*.95)+l(s*.27,s*.25,s*.73,s*.25)+l(s*.30,s*.50,s*.70,s*.36)+l(s*.30,s*.66,s*.70,s*.52);
if(type==='dtr')b=l(s*.5,s*.04,s*.5,s*.96)+l(s*.25,s*.22,s*.75,s*.22)+l(s*.30,s*.44,s*.70,s*.32)+l(s*.30,s*.59,s*.70,s*.47)+l(s*.30,s*.74,s*.70,s*.62);
if(type==='picot')b=`<circle cx="${s/2}" cy="${s*.28}" r="${s*.12}"/>${l(s*.5,s*.40,s*.5,s*.88)}`;
if(type==='ring')b=`<circle cx="${s/2}" cy="${s/2}" r="${s*.30}"/>`;
if(type==='puff')b=[.32,.42,.5,.58,.68].map(x=>`<path d="M ${s*.5} ${s*.84} Q ${s*x} ${s*.35} ${s*.5} ${s*.16}"/>`).join('');
if(type==='cluster')b=[.34,.5,.66].map(x=>`<path d="M ${s*.5} ${s*.86} Q ${s*x} ${s*.48} ${s*.5} ${s*.16}"/>`).join('')+`<circle cx="${s*.5}" cy="${s*.16}" r="${s*.06}"/>`;
if(type==='shell')b=[.2,.35,.5,.65,.8].map(x=>`<path d="M ${s*.5} ${s*.86} Q ${s*x} ${s*.48} ${s*x} ${s*.18}"/>`).join('');
return `<svg width="${s}" height="${s}" viewBox="0 0 ${s} ${s}" fill="none" stroke="${color}" stroke-width="${sw}" stroke-linecap="round" stroke-linejoin="round">${b}</svg>`}
function palette(){stitchesEl.innerHTML='';defs.forEach(d=>{const x=document.createElement('button');x.className='stitch'+(d.id===active?' active':'');x.innerHTML=`<div class="symbol">${svgFor(d.id,28,'#211f1d')}</div><b>${d.name}</b><small>${d.abbr}</small>`;x.onclick=()=>{active=d.id;palette()};stitchesEl.appendChild(x)})}
function snap(){history.push(JSON.stringify(items));if(history.length>60)history.shift();future=[]}
function restore(s){items=JSON.parse(s);selected=null;render()}
function render(){board.querySelectorAll('.placed').forEach(n=>n.remove());hint.style.display=items.length?'none':'block';const color=board.classList.contains('black')?'#f5f1eb':'#211f1d';items.forEach(it=>{const e=document.createElement('div');e.className='placed'+(selected===it.id?' selected':'');e.style.left=it.x+'%';e.style.top=it.y+'%';e.style.transform=`translate(-50%,-50%) rotate(${it.r||0}deg)`;e.innerHTML=svgFor(it.type,it.size,color);e.onpointerdown=ev=>dragStart(ev,it.id);e.onclick=ev=>{ev.stopPropagation();selected=it.id;render()};board.appendChild(e)});status.textContent=`${items.length} stitch${items.length===1?'':'es'}`;const it=items.find(x=>x.id===selected);selectedStatus.textContent=it?(defs.find(d=>d.id===it.type)?.name||it.type)+' selected':'Nothing selected'}
board.onclick=e=>{if(e.target!==board)return;snap();const r=board.getBoundingClientRect();items.push({id:crypto.randomUUID(),type:active,x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100,r:0,size:+size.value});render()};
let drag=null;function dragStart(e,id){e.preventDefault();e.stopPropagation();selected=id;drag={id,sx:e.clientX,sy:e.clientY,orig:{...items.find(x=>x.id===id)},moved:false};window.addEventListener('pointermove',dragMove);window.addEventListener('pointerup',dragEnd,{once:true});render()}
function dragMove(e){if(!drag)return;const d=Math.abs(e.clientX-drag.sx)+Math.abs(e.clientY-drag.sy);if(d<4)return;if(!drag.moved){snap();drag.moved=true}const r=board.getBoundingClientRect(),it=items.find(x=>x.id===drag.id);it.x=Math.max(0,Math.min(100,drag.orig.x+(e.clientX-drag.sx)/r.width*100));it.y=Math.max(0,Math.min(100,drag.orig.y+(e.clientY-drag.sy)/r.height*100));render()}
function dragEnd(){window.removeEventListener('pointermove',dragMove);drag=null}
function mod(fn){const it=items.find(x=>x.id===selected);if(!it)return;snap();fn(it);render()}
rotateL.onclick=()=>mod(i=>i.r=(i.r||0)-15);rotateR.onclick=()=>mod(i=>i.r=(i.r||0)+15);duplicate.onclick=()=>{const it=items.find(x=>x.id===selected);if(!it)return;snap();const c={...it,id:crypto.randomUUID(),x:Math.min(98,it.x+4),y:Math.min(98,it.y+4)};items.push(c);selected=c.id;render()};
delete.onclick=()=>{if(!selected)return;snap();items=items.filter(x=>x.id!==selected);selected=null;render()};clear.onclick=()=>{if(items.length&&confirm('Clear the whole board?')){snap();items=[];selected=null;render()}};undo.onclick=()=>{if(history.length){future.push(JSON.stringify(items));restore(history.pop())}};redo.onclick=()=>{if(future.length){history.push(JSON.stringify(items));restore(future.pop())}};
function theme(black){board.classList.toggle('black',black);blackBtn.classList.toggle('active',black);whiteBtn.classList.toggle('active',!black);render()}whiteBtn.onclick=()=>theme(false);blackBtn.onclick=()=>theme(true);
save.onclick=()=>{localStorage.setItem('crochetPattern',JSON.stringify({name:projectName.value,items,black:board.classList.contains('black')}));alert('Pattern saved on this device.')};load.onclick=()=>{const raw=localStorage.getItem('crochetPattern');if(!raw)return alert('No saved pattern yet.');const d=JSON.parse(raw);snap();items=d.items||[];projectName.value=d.name||'Untitled Pattern';theme(!!d.black)};
export.onclick=()=>{const w=1200,h=800,color=board.classList.contains('black')?'#f5f1eb':'#211f1d',bg=board.classList.contains('black')?'#111':'#fff';let content=items.map(it=>`<g transform="translate(${it.x/100*w} ${it.y/100*h}) rotate(${it.r||0}) translate(${-it.size/2} ${-it.size/2})">${svgFor(it.type,it.size,color).replace(/^<svg[^>]*>|<\/svg>$/g,'')}</g>`).join('');const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><rect width="100%" height="100%" fill="${bg}"/>${content}</svg>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));a.download=(projectName.value||'crochet-pattern').replace(/\s+/g,'-').toLowerCase()+'.svg';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
window.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo.click():undo.click()}if((e.key==='Delete'||e.key==='Backspace')&&document.activeElement.tagName!=='INPUT')document.getElementById('delete').click()};palette();render();