// v8.0 — strict deterministic constructability proof for parameterized lace topology.
(()=>{
  const VERSION='v8.0',role=(g,r,s)=>g.nodes.filter(n=>n.role===r&&(s==null||n.sector===s)),one=(g,r,s)=>role(g,r,s)[0]||null,uid=()=>{try{return crypto.randomUUID()}catch{return'r4-transition-'+Date.now().toString(36)}},seqEq=(a,b)=>a.length===b.length&&a.every((n,i)=>n.type===b[i]);
  function stamp(){window.__CROCHET_CAD_VERSION=VERSION;document.title=`Crochet Pattern Designer · ${VERSION}`;const b=document.querySelector('.brandcopy strong');if(b)b.textContent=`Crochet CAD ${VERSION}`;const p=document.querySelector('#sizingToolsV71 > strong');if(p)p.textContent=`SIZE / GRID · ${VERSION}`;}
  function ensureR4Transition(){const g=window.activeCrochetGraph;if(!g||g.kind!=='lace-flower')return false;if(one(g,'r4-transition-join'))return true;const end=one(g,'inner-petal-stitch-join',5),start=g.nodes.find(n=>n.role==='center-sc'&&n.centerIndex===1);if(!end||!start)return false;const n={id:uid(),type:'slip',round:4,role:'r4-transition-join',group:'r4-transition',sector:1,order:-1,anchor:end.id,workedInto:start.id,topologyOnly:true,visualJoin:true};g.nodes.push(n);try{if(Array.isArray(items)&&!items.some(i=>i.id===n.id)){const t=items.find(i=>i.id===start.id);if(t){items.push({...t,id:n.id,type:'slip',role:n.role,round:4,sector:1,orderInPath:-1,workedInto:start.id,anchor:end.id,visualJoin:true,topologyOnly:true,visualWidth:8,visualHeight:8,footprint:{widthPx:0,heightPx:0,rotationDeg:0,body:false}});render();}}}catch{}return true;}
  function traverse(spaces,start){const seen=new Set();let cur=start;for(let k=0;k<spaces.length;k++){const sp=spaces.find(x=>x.startAnchor===cur&&!seen.has(x.id));if(!sp)return{ok:false,reason:`no space starts at anchor ${cur}`};seen.add(sp.id);cur=sp.endAnchor;}return{ok:seen.size===spaces.length&&cur===start,reason:cur===start?'':`cycle ends at ${cur}`};}
  function chainProof(g,sp,count){if(!sp||sp.chainIds?.length!==count)return false;const ch=sp.chainIds.map(id=>g.nodes.find(n=>n.id===id));if(ch.some(n=>!n||n.type!=='chain'))return false;let prev=sp.startAnchor;for(const n of ch){if(n.anchor!==prev)return false;prev=n.id;}const j=g.nodes.find(n=>n.id===sp.joinId);return!!j&&j.type==='slip'&&j.anchor===prev&&j.workedInto===sp.endAnchor;}
  function audit(){stamp();const g=window.activeCrochetGraph,errors=[],checks=[],pass=(name,ok,detail='')=>{checks.push({name,ok,detail});if(!ok)errors.push(`${name}${detail?': '+detail:''}`)};if(!g||g.kind!=='lace-flower'){const out={ok:false,errors:['No active lace-flower graph'],checks,version:VERSION};window.__LACE_CONSTRUCTABILITY_AUDIT=out;status(out);return out;}ensureR4Transition();const p={innerDc:Number(g.params?.innerDc)||3,middleChain:Number(g.params?.middleChain)||7,outerChain:Number(g.params?.outerChain)||11},ids=new Set(g.nodes.map(n=>n.id)),spids=new Set(g.spaces.map(s=>s.id)),bad=[];for(const n of g.nodes){if(n.workedInto&&!ids.has(n.workedInto)&&!spids.has(n.workedInto))bad.push(`${n.role}.workedInto`);if(n.anchor&&!ids.has(n.anchor))bad.push(`${n.role}.anchor`)}pass('All references resolve',!bad.length,bad.slice(0,5).join(', '));pass('All node IDs unique',ids.size===g.nodes.length);
    const center=one(g,'start'),r1=role(g,'center-sc').sort((a,b)=>a.centerIndex-b.centerIndex),r1j=one(g,'r1-join');pass('R1 exact: MR + 10 sc + closing sl st',center?.type==='ring'&&r1.length===10&&r1.every((n,i)=>n.type==='single'&&n.workedInto===center.id&&n.centerIndex===i)&&r1j?.type==='slip'&&r1j.workedInto===r1[0]?.id);
    const r2=g.spaces.filter(s=>s.round===2);pass('R2 exact five contiguous ch-3 spaces',r2.length===5&&r2.every(sp=>chainProof(g,sp,3))&&traverse(r2,r1[0]?.id).ok);
    const innerSeq=['single','half',...Array(p.innerDc).fill('double'),'half','single'];let r3ok=r2.length===5;for(const sp of r2){const body=role(g,'inner-petal-stitch',sp.sector).sort((a,b)=>a.order-b.order),j=one(g,'inner-petal-stitch-join',sp.sector);if(!seqEq(body,innerSeq)||!body.every(n=>n.workedInto===sp.id)||j?.workedInto!==sp.endAnchor)r3ok=false}pass(`R3 exact: sc, hdc, ${p.innerDc} dc, hdc, sc ×5`,r3ok);
    const tr=one(g,'r4-transition-join'),r3end=one(g,'inner-petal-stitch-join',5),r4start=r1[1];pass('R3→R4 explicit reachable sl st',tr?.anchor===r3end?.id&&tr?.workedInto===r4start?.id);
    const r4=g.spaces.filter(s=>s.round===4);pass(`R4 exact five contiguous ch-${p.middleChain} spaces`,r4.length===5&&r4.every(sp=>chainProof(g,sp,p.middleChain))&&traverse(r4,r4start?.id).ok);
    const mid=['single','half','double','double','treble','treble','treble','double','double','half','single'];let r5ok=r4.length===5;for(const sp of r4){const body=role(g,'mid-petal-stitch',sp.sector).sort((a,b)=>a.order-b.order),j=one(g,'mid-petal-stitch-join',sp.sector);if(!seqEq(body,mid)||!body.every(n=>n.workedInto===sp.id)||j?.workedInto!==sp.endAnchor)r5ok=false}pass('R5 exact 11-stitch petals ×5',r5ok);
    const r5end=one(g,'mid-petal-stitch-join',5),r6=g.spaces.filter(s=>s.round===6);pass(`R6 exact five contiguous ch-${p.outerChain} spaces from fifth R5 join`,r6.length===5&&r6.every(sp=>chainProof(g,sp,p.outerChain))&&traverse(r6,r5end?.id).ok);
    const outerSeq=['single','half','double','double','treble','treble','treble','dtr','dtr','dtr','treble','treble','treble','double','double','half','single'];let r7ok=r6.length===5;for(const sp of r6){const body=role(g,'outer-petal-stitch',sp.sector).sort((a,b)=>a.order-b.order),j=one(g,'outer-petal-stitch-join',sp.sector);if(!seqEq(body,outerSeq)||!body.every(n=>n.workedInto===sp.id)||j?.workedInto!==sp.endAnchor)r7ok=false}pass('R7 exact 17-stitch petals ×5',r7ok);
    const outer=role(g,'outer-petal-stitch'),edge=role(g,'edge-sc');let edgeOk=edge.length===95&&outer.length===85;for(const base of outer){const mapped=edge.filter(e=>e.workedInto===base.id),want=base.order===8?3:1;if(mapped.length!==want||mapped.some(e=>e.type!=='single'))edgeOk=false}pass('R8 exact mapping; center dtr gets 3 sc; total 95 sc',edgeOk);
    const expected={0:1,1:11,2:20,3:5*(p.innerDc+5),4:1+5*(p.middleChain+1),5:60,6:5*(p.outerChain+1),7:90,8:100},actual={};for(const n of g.nodes)actual[n.round]=(actual[n.round]||0)+1;pass('Round node totals match selected parameters',Object.entries(expected).every(([r,c])=>actual[r]===c),JSON.stringify(actual));const layout=window.__LACE_LAYOUT_SNAPSHOT?.validation;pass('Geometry/layout passes',layout?.ok===true,(layout?.errors||[]).join(' · '));const out={ok:!errors.length,errors,checks,params:p,version:VERSION,proofType:'parameterized-deterministic-topology-proof',checkedAt:new Date().toISOString()};window.__LACE_CONSTRUCTABILITY_AUDIT=out;g.constructability=out;status(out);return out;}
  function status(a){const panel=document.getElementById('sizingToolsV71');if(panel){let e=document.getElementById('constructabilityStatusV78');if(!e){e=document.createElement('div');e.id='constructabilityStatusV78';e.style.cssText='margin-top:10px;padding:8px 9px;border-radius:7px;font:800 11px/1.35 system-ui';panel.appendChild(e)}e.style.background=a.ok?'rgba(28,120,68,.2)':'rgba(180,45,45,.2)';e.style.border=`1px solid ${a.ok?'#2aa45f':'#d55454'}`;e.style.color=a.ok?'#8ff0b8':'#ffabab';e.textContent=`CONSTRUCTABILITY PROOF: ${a.ok?'PASS':'FAIL'}${a.ok?' · selected topology verified':` · ${a.errors[0]||'audit failed'}`}`;}}
  window.runLaceConstructabilityAudit=audit;document.addEventListener('click',e=>{if(e.target?.id==='laceImport')setTimeout(()=>audit(),100);if(['exportPdfBtn','mobileExportPdfBtn','quickExportPdfBtn'].includes(e.target?.id)&&window.activeCrochetGraph?.kind==='lace-flower'){const a=audit();if(!a.ok){e.preventDefault();e.stopImmediatePropagation();alert('CONSTRUCTABILITY PROOF FAIL\n'+a.errors.join('\n'));}}},true);setTimeout(()=>{stamp();if(window.activeCrochetGraph?.kind==='lace-flower')audit();},180);
})();