// v8.4 — verifier-only constructability audit. Proof contracts MUST originate in the generator.
(()=>{
  const VERSION='v8.4',role=(g,r,s)=>g.nodes.filter(n=>n.role===r&&(s==null||n.sector===s)),one=(g,r,s)=>role(g,r,s)[0]||null,seqEq=(a,b)=>a.length===b.length&&a.every((n,i)=>n.type===b[i]);
  function stamp(){window.__CROCHET_CAD_VERSION=VERSION;document.title=`Crochet Pattern Designer · ${VERSION}`;const b=document.querySelector('.brandcopy strong');if(b)b.textContent=`Crochet CAD ${VERSION}`;const p=document.querySelector('#sizingToolsV71 > strong');if(p)p.textContent=`SIZE / GRID · ${VERSION}`;}
  function traverse(spaces,start){const seen=new Set();let cur=start;for(let k=0;k<spaces.length;k++){const sp=spaces.find(x=>x.startAnchor===cur&&!seen.has(x.id));if(!sp)return{ok:false,reason:`no space starts at anchor ${cur}`};seen.add(sp.id);cur=sp.endAnchor;}return{ok:seen.size===spaces.length&&cur===start,reason:cur===start?'':`cycle ends at ${cur}`};}
  function chainProof(g,sp,count){if(!sp||sp.chainIds?.length!==count)return false;const ch=sp.chainIds.map(id=>g.nodes.find(n=>n.id===id));if(ch.some(n=>!n||n.type!=='chain'))return false;let prev=sp.startAnchor;for(const n of ch){if(n.anchor!==prev)return false;prev=n.id;}const j=g.nodes.find(n=>n.id===sp.joinId);return!!j&&j.type==='slip'&&j.anchor===prev&&j.workedInto===sp.endAnchor;}
  function audit(){stamp();const g=window.activeCrochetGraph,errors=[],checks=[],pass=(name,ok,detail='')=>{checks.push({name,ok,detail});if(!ok)errors.push(`${name}${detail?': '+detail:''}`)};if(!g||g.kind!=='lace-flower'){const out={ok:false,errors:['No active lace-flower graph'],checks,version:VERSION};window.__LACE_CONSTRUCTABILITY_AUDIT=out;status(out);return out;}
    const p={innerDc:Number(g.params?.innerDc)||3,middleChain:Number(g.params?.middleChain)||7,outerChain:Number(g.params?.outerChain)||11},ids=new Set(g.nodes.map(n=>n.id)),spids=new Set(g.spaces.map(s=>s.id)),bad=[];
    for(const n of g.nodes){if(n.workedInto&&!ids.has(n.workedInto)&&!spids.has(n.workedInto))bad.push(`${n.role}.workedInto`);if(n.anchor&&!ids.has(n.anchor))bad.push(`${n.role}.anchor`)}
    pass('Generator-native proof model',g.proofModel?.source==='crochet-construction-logic');
    pass('Generator-native space coverage contracts',Array.isArray(g.spaceCoverageContracts)&&g.spaceCoverageContracts.length===3);
    pass('Generator-native stitch coverage contract',Array.isArray(g.coverageContracts)&&g.coverageContracts.some(c=>c.step===8&&c.expectedBaseCount===85&&c.expectedOutputCount===95&&c.expectedDelta===10));
    const proofRoles=['inner-petal-stitch','mid-petal-stitch','outer-petal-stitch','edge-sc'],proofNodes=g.nodes.filter(n=>proofRoles.includes(n.role));
    pass('Generator-native consumes/produces/countsAsStitch',proofNodes.length>0&&proofNodes.every(n=>Array.isArray(n.consumes)&&n.consumes.length===1&&n.produces===1&&n.countsAsStitch===true));
    pass('All references resolve',!bad.length,bad.slice(0,5).join(', '));pass('All node IDs unique',ids.size===g.nodes.length);
    const spaceCore=typeof window.validateCrochetSpaceCoverageContracts==='function'?window.validateCrochetSpaceCoverageContracts(g):{ok:false,errors:[{message:'Generic space coverage validator not loaded'}],proofs:[]};g.spaceCoreValidation=spaceCore;pass('Generic R3/R5/R7 chain-space repeat coverage proof',spaceCore.ok,(spaceCore.errors||[]).slice(0,3).map(x=>x.message||x.code||String(x)).join(' · '));
    const core=typeof window.validateCrochetPatternGraph==='function'?window.validateCrochetPatternGraph(g):{ok:false,errors:[{message:'Pattern Core validator not loaded'}],warnings:[]};g.coreValidation=core;pass('Pattern Core structural + stitch-math validation',core.ok,(core.errors||[]).slice(0,3).map(x=>x.message||x.code||String(x)).join(' · '));
    const center=one(g,'start'),r1=role(g,'center-sc').sort((a,b)=>a.centerIndex-b.centerIndex),r1j=one(g,'r1-join');pass('R1 exact: MR + 10 sc + closing sl st',center?.type==='ring'&&r1.length===10&&r1.every((n,i)=>n.type==='single'&&n.workedInto===center.id&&n.centerIndex===i)&&r1j?.workedInto===r1[0]?.id);
    const r2=g.spaces.filter(s=>s.round===2);pass('R2 exact five contiguous ch-3 spaces',r2.length===5&&r2.every(sp=>chainProof(g,sp,3))&&traverse(r2,r1[0]?.id).ok);
    const innerSeq=['single','half',...Array(p.innerDc).fill('double'),'half','single'];let r3ok=r2.length===5;for(const sp of r2){const body=role(g,'inner-petal-stitch',sp.sector).sort((a,b)=>a.order-b.order),j=one(g,'inner-petal-stitch-join',sp.sector);if(!seqEq(body,innerSeq)||!body.every(n=>n.workedInto===sp.id)||j?.workedInto!==sp.endAnchor)r3ok=false}pass(`R3 exact: sc, hdc, ${p.innerDc} dc, hdc, sc ×5`,r3ok);
    const tr=one(g,'r4-transition-join'),r3end=one(g,'inner-petal-stitch-join',5),r4start=r1[1];pass('R3→R4 explicit reachable sl st',tr?.anchor===r3end?.id&&tr?.workedInto===r4start?.id);
    const r4=g.spaces.filter(s=>s.round===4);pass(`R4 exact five contiguous ch-${p.middleChain} spaces`,r4.length===5&&r4.every(sp=>chainProof(g,sp,p.middleChain))&&traverse(r4,r4start?.id).ok);
    const mid=['single','half','double','double','treble','treble','treble','double','double','half','single'];let r5ok=r4.length===5;for(const sp of r4){const body=role(g,'mid-petal-stitch',sp.sector).sort((a,b)=>a.order-b.order),j=one(g,'mid-petal-stitch-join',sp.sector);if(!seqEq(body,mid)||!body.every(n=>n.workedInto===sp.id)||j?.workedInto!==sp.endAnchor)r5ok=false}pass('R5 exact 11-stitch petals ×5',r5ok);
    const r5end=one(g,'mid-petal-stitch-join',5),r6=g.spaces.filter(s=>s.round===6);pass(`R6 exact five contiguous ch-${p.outerChain} spaces`,r6.length===5&&r6.every(sp=>chainProof(g,sp,p.outerChain))&&traverse(r6,r5end?.id).ok);
    const outerSeq=['single','half','double','double','treble','treble','treble','dtr','dtr','dtr','treble','treble','treble','double','double','half','single'];let r7ok=r6.length===5;for(const sp of r6){const body=role(g,'outer-petal-stitch',sp.sector).sort((a,b)=>a.order-b.order),j=one(g,'outer-petal-stitch-join',sp.sector);if(!seqEq(body,outerSeq)||!body.every(n=>n.workedInto===sp.id)||j?.workedInto!==sp.endAnchor)r7ok=false}pass('R7 exact 17-stitch petals ×5',r7ok);
    const outer=role(g,'outer-petal-stitch'),edge=role(g,'edge-sc');let edgeOk=edge.length===95&&outer.length===85;for(const base of outer){const mapped=edge.filter(e=>e.workedInto===base.id),want=base.order===8?3:1;if(mapped.length!==want||mapped.some(e=>e.type!=='single'))edgeOk=false}pass('R8 exact mapping; center dtr gets 3 sc; total 95 sc',edgeOk);
    const layout=window.__LACE_LAYOUT_SNAPSHOT?.validation;pass('Geometry/layout passes',layout?.ok===true,(layout?.errors||[]).join(' · '));const out={ok:!errors.length,errors,checks,params:p,version:VERSION,proofType:'generator-native-contracts+deterministic-topology+generic-pattern-core+space-repeat+stitch-coverage',coreValidation:core,spaceCoreValidation:spaceCore,proofModel:g.proofModel,checkedAt:new Date().toISOString()};window.__LACE_CONSTRUCTABILITY_AUDIT=out;g.constructability=out;status(out);return out;}
  function status(a){const panel=document.getElementById('sizingToolsV71');if(panel){let e=document.getElementById('constructabilityStatusV78');if(!e){e=document.createElement('div');e.id='constructabilityStatusV78';e.style.cssText='margin-top:10px;padding:8px 9px;border-radius:7px;font:800 11px/1.35 system-ui';panel.appendChild(e)}e.style.background=a.ok?'rgba(28,120,68,.2)':'rgba(180,45,45,.2)';e.style.border=`1px solid ${a.ok?'#2aa45f':'#d55454'}`;e.style.color=a.ok?'#8ff0b8':'#ffabab';e.textContent=`CONSTRUCTABILITY PROOF: ${a.ok?'PASS':'FAIL'}${a.ok?' · generator evidence verified':` · ${a.errors[0]||'audit failed'}`}`;}}
  window.runLaceConstructabilityAudit=audit;document.addEventListener('click',e=>{if(e.target?.id==='laceImport')setTimeout(()=>audit(),100);if(['exportPdfBtn','mobileExportPdfBtn','quickExportPdfBtn'].includes(e.target?.id)&&window.activeCrochetGraph?.kind==='lace-flower'){const a=audit();if(!a.ok){e.preventDefault();e.stopImmediatePropagation();alert('CONSTRUCTABILITY PROOF FAIL\n'+a.errors.join('\n'));}}},true);setTimeout(()=>{stamp();if(window.activeCrochetGraph?.kind==='lace-flower')audit();},180);
})();