// v7.5 PDF exporter — honors open stitch size and independent line weight.
(()=>{
  const SCALE_KEY='crochetCad.stitchStyleV75';
  function settings(){try{const s=JSON.parse(localStorage.getItem(SCALE_KEY)||'{}');return{size:Math.max(.01,(Number(s.sizePct)||100)/100),line:Math.max(.01,(Number(s.linePct)||100)/100)}}catch{return{size:1,line:1}}}
  function visible(){try{return items.filter(i=>!i.visualJoin)}catch{return[]}}
  function px(it){if(it.generatedPattern&&Number.isInteger(it.gridCol)&&Number.isInteger(it.gridRow))return{x:it.gridCol*24,y:it.gridRow*24};const bw=document.getElementById('board')?.clientWidth||2200;return{x:(it.x/100)*bw,y:it.y||0}}
  function metric(it){const m=window.CROCHET_STITCH_METRICS?.[it.type];return{w:it.visualWidth||m?.visualWidthPx||40,h:it.visualHeight||m?.visualHeightPx||40}}
  function bounds(src,size){const bb=src.map(it=>{const p=px(it),m=metric(it);return{minX:p.x-m.w*size/2,maxX:p.x+m.w*size/2,minY:p.y-m.h*size/2,maxY:p.y+m.h*size/2}});const pad=80;return{minX:Math.min(...bb.map(b=>b.minX))-pad,maxX:Math.max(...bb.map(b=>b.maxX))+pad,minY:Math.min(...bb.map(b=>b.minY))-pad,maxY:Math.max(...bb.map(b=>b.maxY))+pad}}
  function line(ctx,a,b,c,d){ctx.beginPath();ctx.moveTo(a,b);ctx.lineTo(c,d);ctx.stroke()}
  function draw(ctx,type,x,y,size,rotation,lineScale){ctx.save();ctx.translate(x,y);ctx.rotate((rotation||0)*Math.PI/180);ctx.strokeStyle='#111';ctx.fillStyle='#111';ctx.lineWidth=Math.max(.35,(size/16)*lineScale);ctx.lineCap='round';ctx.lineJoin='round';const s=size;if(type==='chain'){ctx.beginPath();ctx.ellipse(0,0,s*.34,s*.14,0,0,Math.PI*2);ctx.stroke()}else if(type==='slip'){ctx.beginPath();ctx.arc(0,0,s*.1,0,Math.PI*2);ctx.fill()}else if(type==='single'){line(ctx,-s*.25,-s*.25,s*.25,s*.25);line(ctx,s*.25,-s*.25,-s*.25,s*.25)}else if(type==='half'){line(ctx,0,-s*.4,0,s*.4);line(ctx,-s*.23,-s*.15,s*.23,-s*.15)}else if(type==='double'){line(ctx,0,-s*.42,0,s*.42);line(ctx,-s*.23,-s*.2,s*.23,-s*.2);line(ctx,-s*.2,s*.05,s*.2,-s*.1)}else if(type==='treble'||type==='dtr'){line(ctx,0,-s*.44,0,s*.44);line(ctx,-s*.23,-s*.23,s*.23,-s*.23);const n=type==='dtr'?3:2;for(let k=0;k<n;k++){const yy=-s*.02+k*s*.15;line(ctx,-s*.2,yy+s*.08,s*.2,yy-s*.08)}}else if(type==='ring'){ctx.beginPath();ctx.arc(0,0,s*.3,0,Math.PI*2);ctx.stroke()}else if(type==='picot'){ctx.beginPath();ctx.arc(0,-s*.2,s*.12,0,Math.PI*2);ctx.stroke();line(ctx,0,-s*.08,0,s*.38)}else if(['puff','bobble','cluster','shell'].includes(type)){const count=type==='shell'?5:(type==='cluster'?3:5);for(let k=0;k<count;k++){const spread=(k-(count-1)/2)*s*.12;ctx.beginPath();ctx.moveTo(0,s*.35);ctx.quadraticCurveTo(spread,-s*.05,spread,-s*.34);ctx.stroke()}if(type==='cluster'){ctx.beginPath();ctx.arc(0,-s*.34,s*.05,0,Math.PI*2);ctx.fill()}}else line(ctx,-s*.2,0,s*.2,0);ctx.restore()}
  function canvas(){const src=visible();if(!src.length)return null;const st=settings(),b=bounds(src,st.size),rawW=Math.max(1,b.maxX-b.minX),rawH=Math.max(1,b.maxY-b.minY),maxDim=2600,fit=Math.min(2,maxDim/Math.max(rawW,rawH)),c=document.createElement('canvas');c.width=Math.max(420,Math.round(rawW*fit));c.height=Math.max(420,Math.round(rawH*fit));const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);for(const it of src){const p=px(it),m=metric(it),base=Math.max(m.w,m.h);draw(ctx,it.type,(p.x-b.minX)*fit,(p.y-b.minY)*fit,base*fit*st.size,it.rotation||0,st.line)}return c}
  async function exportV75(){const src=visible();if(!src.length){alert('There is no pattern to export yet.');return}const v=window.__LACE_LAYOUT_SNAPSHOT?.validation;if(src.some(i=>i.patternKind==='lace-flower')&&!v?.ok){alert('LAYOUT REJECTED\n'+(v?.errors?.join(' · ')||'Layout has not passed validation.'));return}try{const{jsPDF}=await import('https://cdn.jsdelivr.net/npm/jspdf@2.5.2/+esm'),doc=new jsPDF({unit:'pt',format:'a4'}),margin=44,pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight(),chart=canvas(),st=settings();doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('Crochet Diagram',margin,46);doc.setFont('helvetica','normal');doc.setFontSize(9.5);doc.text(`Stitch size: ${Math.round(st.size*100)}%   Line weight: ${Math.round(st.line*100)}%`,margin,64);if(chart){const maxW=pw-margin*2,maxH=ph-150,fit=Math.min(maxW/chart.width,maxH/chart.height),w=chart.width*fit,h=chart.height*fit;doc.addImage(chart.toDataURL('image/png'),'PNG',(pw-w)/2,84,w,h,undefined,'FAST')}doc.addPage();doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text('Written Pattern',margin,52);doc.setFont('helvetica','normal');doc.setFontSize(10.5);const text=typeof window.buildEnglishWrittenPattern==='function'?window.buildEnglishWrittenPattern():'Written pattern unavailable.';const lines=doc.splitTextToSize(text,pw-margin*2);let y=78;for(const l of lines){if(y>ph-48){doc.addPage();y=50}doc.text(l,margin,y);y+=14}doc.save('crochet-geometric-pattern.pdf')}catch(err){console.error(err);alert('Could not create PDF. Please check your connection and try again.')}}
  const ids=['exportPdfBtn','mobileExportPdfBtn','quickExportPdfBtn'];document.addEventListener('click',e=>{if(ids.includes(e.target?.id)){e.preventDefault();e.stopImmediatePropagation();exportV75()}},true);window.exportPatternPdfV75=exportV75;
})();
