const exportPdfBtn=document.getElementById('exportPdfBtn');
const mobileExportPdfBtn=document.getElementById('mobileExportPdfBtn');
const quickExportPdfBtn=document.getElementById('quickExportPdfBtn');

function stitchAbbr(type){return ({chain:'ch',slip:'sl st',single:'sc',half:'hdc',double:'dc',treble:'tr',dtr:'dtr',picot:'picot',puff:'puff',cluster:'cl',shell:'shell',ring:'MR'})[type]||type;}
function compressStitches(list){
  if(!list.length)return '';
  const out=[];let last=list[0],count=1;
  const flush=()=>{out.push((count>1?count+' ':'')+stitchAbbr(last));};
  for(let i=1;i<list.length;i++){
    if(list[i]===last)count++;
    else{flush();last=list[i];count=1;}
  }
  flush();return out.join(', ');
}
function buildEnglishWrittenPattern(){
  if(!items.length)return 'No stitches on the board.';
  const photoRound=items.some(i=>i.photoDraft&&Number.isFinite(i.round)&&i.round>0);
  const writtenRound=items.some(i=>i.writtenDraft&&Number.isFinite(i.round)&&i.round>0);
  const isRound=photoRound||writtenRound;
  const groups=new Map();
  for(const it of items){
    if(it.type==='ring')continue;
    const key=isRound?(Number.isFinite(it.round)?it.round:it.row+1):(it.row+1);
    if(!groups.has(key))groups.set(key,[]);
    groups.get(key).push(it);
  }
  const lines=[];
  lines.push(isRound?'Crochet Pattern - Round Construction':'Crochet Pattern - Row Construction','');
  if(items.some(i=>i.type==='ring'))lines.push('Start with a Magic Ring (MR).','');
  for(const [key,group] of [...groups.entries()].sort((a,b)=>a[0]-b[0])){
    const ordered=[...group].sort((a,b)=>a.col-b.col);
    lines.push(`${isRound?'Round':'Row'} ${key}: ${compressStitches(ordered.map(i=>i.type))}. (${ordered.length} sts)`);
  }
  lines.push('','Notes:','- This is an editable reconstructed pattern generated from the current chart.','- Estimated stitch counts should be reviewed before crocheting.');
  return lines.join('\n');
}
async function exportPatternPdf(){
  if(!items.length){alert('There is no pattern to export yet.');return;}
  try{
    const {jsPDF}=await import('https://cdn.jsdelivr.net/npm/jspdf@2.5.2/+esm');
    const doc=new jsPDF({unit:'pt',format:'a4'});
    const margin=48,pageW=doc.internal.pageSize.getWidth(),pageH=doc.internal.pageSize.getHeight();
    doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('Crochet Pattern Report',margin,60);
    doc.setFont('helvetica','normal');doc.setFontSize(10);doc.text('Generated by Crochet CAD',margin,78);
    doc.setFontSize(11);
    const lines=doc.splitTextToSize(buildEnglishWrittenPattern(),pageW-margin*2);
    let y=108;
    for(const line of lines){if(y>pageH-55){doc.addPage();y=55;}doc.text(line,margin,y);y+=15;}
    doc.save('crochet-pattern-report.pdf');
  }catch(err){alert('Could not create PDF. Please check your connection and try again.');}
}
exportPdfBtn?.addEventListener('click',exportPatternPdf);
mobileExportPdfBtn?.addEventListener('click',exportPatternPdf);
quickExportPdfBtn?.addEventListener('click',exportPatternPdf);
window.buildEnglishWrittenPattern=buildEnglishWrittenPattern;
