const exportPdfBtn=document.getElementById('exportPdfBtn');
const mobileExportPdfBtn=document.getElementById('mobileExportPdfBtn');
const quickExportPdfBtn=document.getElementById('quickExportPdfBtn');
function stitchAbbr(type){return({chain:'ch',slip:'sl st',single:'sc',half:'hdc',double:'dc',treble:'tr',dtr:'dtr',picot:'picot',puff:'puff',bobble:'bobble',cluster:'cl',shell:'shell',ring:'MR'})[type]||type;}
function stitchName(type){return defs.find(d=>d.id===type)?.name||type;}
function visibleExportItems(){return items.filter(i=>!i.visualJoin);}
function compressStitches(list,approx=false){if(!list.length)return'';const out=[];let last=list[0],count=1;const flush=()=>out.push(`${count>1?(approx?'~':'')+count+' ':''}${stitchAbbr(last)}`);for(let i=1;i<list.length;i++){if(list[i]===last)count++;else{flush();last=list[i];count=1;}}flush();return out.join(', ');}
function geometryGroups(){const map=new Map();for(const it of visibleExportItems()){if(it.type==='ring'&&it.pathId==='CENTER')continue;const key=it.pathId||`path-${(it.row||0)+1}`;if(!map.has(key))map.set(key,[]);map.get(key).push(it);}return[...map.entries()].map(([id,g])=>[id,g.sort((a,b)=>(a.orderInPath??a.col??0)-(b.orderInPath??b.col??0))]);}
function buildEnglishWrittenPattern(){
 if(!items.length)return'No stitches on the board.';
 const active=window.activeCrochetGraph;if(active?.validation?.ok&&typeof active.written==='string'&&active.written.trim())return active.written;
 const source=visibleExportItems(),isGeometry=source.some(i=>i.geometryDraft);
 if(isGeometry){const lines=['Geometric Crochet Reconstruction',''];if(source.some(i=>i.type==='ring'))lines.push('Center: Begin with a Magic Ring (MR) where shown.','');const groups=geometryGroups();groups.forEach(([id,g],index)=>{const region=g[0]?.sourceRegion||`Path ${index+1}`,approx=g.some(i=>i.estimated),count=g.length;lines.push(`${region} (${id}): ${compressStitches(g.map(i=>i.type),approx)}. (${approx?'~':''}${count} sts/groups)`);if(index>0){const prev=groups[index-1][1].length,delta=count-prev;if(Math.abs(delta)>=2)lines.push(`  Geometry change: ${delta>0?'increase':'decrease'} by approximately ${Math.abs(delta)} placements relative to the previous path.`);}});lines.push('','Construction notes:','- Follow paths in the order shown on the final diagram.','- Chain paths mark preserved openings or bridging spaces.','- Rotated symbols follow local contour direction.','- Counts marked ~ are geometric estimates derived from the final diagram and should be checked before crocheting.');return lines.join('\n');}
 const squareMotif=source.some(i=>i.photoDraft&&i.photoGeometry==='square'&&Number.isFinite(i.round)),photoRound=source.some(i=>i.photoDraft&&Number.isFinite(i.round)&&i.round>0),writtenRound=source.some(i=>i.writtenDraft&&Number.isFinite(i.round)&&i.round>0),isRound=photoRound||writtenRound,groups=new Map();for(const it of source){if(it.type==='ring')continue;const key=isRound?(Number.isFinite(it.round)?it.round:it.row+1):(it.row+1);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(it);}const lines=[squareMotif?'Crochet Pattern - Square Motif Construction':(isRound?'Crochet Pattern - Round Construction':'Crochet Pattern - Path Construction'),''];if(source.some(i=>i.type==='ring'))lines.push('Start with a Magic Ring (MR).','');for(const[key,group]of[...groups.entries()].sort((a,b)=>a[0]-b[0])){const ordered=[...group].sort((a,b)=>(a.col??a.orderInPath??0)-(b.col??b.orderInPath??0)),label=squareMotif?'Square Round':(isRound?'Round':'Path');lines.push(`${label} ${key}: ${compressStitches(ordered.map(i=>i.type),group.some(i=>i.estimated))}. (${group.some(i=>i.estimated)?'~':''}${ordered.length} sts/groups)`);}lines.push('','Notes:','- Written instructions are generated from the current final diagram.','- Estimated counts should be reviewed before crocheting.');return lines.join('\n');
}
function exportItemPx(it){if(it.generatedPattern&&Number.isInteger(it.gridCol)&&Number.isInteger(it.gridRow))return{x:it.gridCol*24,y:it.gridRow*24};const bw=board.clientWidth||2200;return{x:(it.x/100)*bw,y:it.y||0};}
function itemVisualBounds(it){const p=exportItemPx(it),w=it.visualWidth||window.CROCHET_STITCH_METRICS?.[it.type]?.visualWidthPx||40,h=it.visualHeight||window.CROCHET_STITCH_METRICS?.[it.type]?.visualHeightPx||40;return{minX:p.x-w/2,maxX:p.x+w/2,minY:p.y-h/2,maxY:p.y+h/2};}
function chartBounds(){const source=visibleExportItems();if(!source.length)return null;const bb=source.map(itemVisualBounds),pad=80;return{minX:Math.min(...bb.map(b=>b.minX))-pad,maxX:Math.max(...bb.map(b=>b.maxX))+pad,minY:Math.min(...bb.map(b=>b.minY))-pad,maxY:Math.max(...bb.map(b=>b.maxY))+pad};}
function drawLine(ctx,x1,y1,x2,y2){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
function drawCrochetSymbol(ctx,type,x,y,size,rotation=0){ctx.save();ctx.translate(x,y);ctx.rotate((rotation||0)*Math.PI/180);ctx.strokeStyle='#111';ctx.fillStyle='#111';ctx.lineWidth=Math.max(1.5,size/16);ctx.lineCap='round';ctx.lineJoin='round';const s=size;if(type==='chain'){ctx.beginPath();ctx.ellipse(0,0,s*.34,s*.14,0,0,Math.PI*2);ctx.stroke();}else if(type==='slip'){ctx.beginPath();ctx.arc(0,0,s*.1,0,Math.PI*2);ctx.fill();}else if(type==='single'){drawLine(ctx,-s*.25,-s*.25,s*.25,s*.25);drawLine(ctx,s*.25,-s*.25,-s*.25,s*.25);}else if(type==='half'){drawLine(ctx,0,-s*.4,0,s*.4);drawLine(ctx,-s*.23,-s*.15,s*.23,-s*.15);}else if(type==='double'){drawLine(ctx,0,-s*.42,0,s*.42);drawLine(ctx,-s*.23,-s*.2,s*.23,-s*.2);drawLine(ctx,-s*.2,s*.05,s*.2,-s*.1);}else if(type==='treble'||type==='dtr'){drawLine(ctx,0,-s*.44,0,s*.44);drawLine(ctx,-s*.23,-s*.23,s*.23,-s*.23);const n=type==='dtr'?3:2;for(let k=0;k<n;k++){const yy=-s*.02+k*s*.15;drawLine(ctx,-s*.2,yy+s*.08,s*.2,yy-s*.08);}}else if(type==='ring'){ctx.beginPath();ctx.arc(0,0,s*.3,0,Math.PI*2);ctx.stroke();}else if(type==='picot'){ctx.beginPath();ctx.arc(0,-s*.2,s*.12,0,Math.PI*2);ctx.stroke();drawLine(ctx,0,-s*.08,0,s*.38);}else if(['puff','bobble','cluster','shell'].includes(type)){const count=type==='shell'?5:(type==='cluster'?3:5);for(let k=0;k<count;k++){const spread=(k-(count-1)/2)*s*.12;ctx.beginPath();ctx.moveTo(0,s*.35);ctx.quadraticCurveTo(spread,-s*.05,spread,-s*.34);ctx.stroke();}if(type==='cluster'){ctx.beginPath();ctx.arc(0,-s*.34,s*.05,0,Math.PI*2);ctx.fill();}}else drawLine(ctx,-s*.2,0,s*.2,0);ctx.restore();}
function renderChartCanvas(){const b=chartBounds();if(!b)return null;const source=visibleExportItems(),rawW=Math.max(1,b.maxX-b.minX),rawH=Math.max(1,b.maxY-b.minY),maxDim=1900,scale=Math.min(1.9,maxDim/Math.max(rawW,rawH)),canvas=document.createElement('canvas');canvas.width=Math.max(420,Math.round(rawW*scale));canvas.height=Math.max(420,Math.round(rawH*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#dbe0e4';ctx.lineWidth=1;ctx.setLineDash([5,6]);if(source.some(i=>i.geometryDraft)){for(const[,g]of geometryGroups()){if(g.length<2)continue;for(let i=0;i<g.length;i++){const a=exportItemPx(g[i]),z=exportItemPx(g[(i+1)%g.length]);drawLine(ctx,(a.x-b.minX)*scale,(a.y-b.minY)*scale,(z.x-b.minX)*scale,(z.y-b.minY)*scale);}}}ctx.setLineDash([]);for(const it of source){const p=exportItemPx(it),metric=window.CROCHET_STITCH_METRICS?.[it.type],symbolSize=it.generatedPattern?Math.max(metric?.visualWidthPx||18,metric?.visualHeightPx||18):(it.geometryDraft?30:40);drawCrochetSymbol(ctx,it.type,(p.x-b.minX)*scale,(p.y-b.minY)*scale,symbolSize*scale,it.rotation||0);}return canvas;}
function usedLegend(){return[...new Set(visibleExportItems().map(i=>i.type))].map(t=>({type:t,name:stitchName(t),abbr:stitchAbbr(t)}));}
function laceExportValidation(){if(!items.some(i=>i.patternKind==='lace-flower'))return{ok:true};const v=window.__LACE_LAYOUT_SNAPSHOT?.validation;if(!v?.ok)return{ok:false,reason:v?.errors?.join(' · ')||'Lace flower layout has not passed geometry validation.'};return{ok:true};}
async function exportPatternPdf(){if(!items.length){alert('There is no pattern to export yet.');return;}const gate=laceExportValidation();if(!gate.ok){alert('LAYOUT REJECTED\n'+gate.reason);return;}try{const{jsPDF}=await import('https://cdn.jsdelivr.net/npm/jspdf@2.5.2/+esm'),doc=new jsPDF({unit:'pt',format:'a4'}),margin=44,pageW=doc.internal.pageSize.getWidth(),pageH=doc.internal.pageSize.getHeight(),geometry=items.some(i=>i.geometryDraft);doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('Crochet Diagram',margin,46);doc.setFont('helvetica','normal');doc.setFontSize(10.5);doc.text(geometry?'Geometric stitch reconstruction':'Editable crochet diagram',margin,64);const chart=renderChartCanvas();if(chart){const legendH=Math.min(120,28+Math.ceil(usedLegend().length/3)*24),maxW=pageW-margin*2,maxH=pageH-150-legendH,fit=Math.min(maxW/chart.width,maxH/chart.height),w=chart.width*fit,h=chart.height*fit,x=(pageW-w)/2,y=84;doc.addImage(chart.toDataURL('image/png'),'PNG',x,y,w,h,undefined,'FAST');let ly=Math.min(pageH-legendH+18,y+h+30);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('Legend',margin,ly);ly+=16;doc.setFont('helvetica','normal');doc.setFontSize(9);usedLegend().forEach((e,i)=>{const col=i%3,row=Math.floor(i/3),x0=margin+col*((pageW-margin*2)/3);doc.text(`${e.name} (${e.abbr})`,x0,ly+row*18);});}doc.addPage();doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text('Written Pattern',margin,52);doc.setFont('helvetica','normal');doc.setFontSize(10.5);const lines=doc.splitTextToSize(buildEnglishWrittenPattern(),pageW-margin*2);let y=78;for(const line of lines){if(y>pageH-48){doc.addPage();y=50;}doc.text(line,margin,y);y+=14;}if(geometry){doc.addPage();doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text('Geometry Summary',margin,52);doc.setFont('helvetica','normal');doc.setFontSize(10);const groups=geometryGroups(),types=[...new Set(items.map(i=>i.geometryType).filter(Boolean))],regions=[...new Set(items.map(i=>i.sourceRegion).filter(Boolean))],confidence=items.filter(i=>Number.isFinite(i.confidence));const avg=confidence.length?Math.round(confidence.reduce((s,i)=>s+i.confidence,0)/confidence.length*100):null;const summary=[`Construction paths: ${groups.length}`,`Regions: ${regions.join(', ')||'—'}`,`Geometry types: ${types.join(', ')||'—'}`,`Stitch families: ${usedLegend().map(x=>x.name).join(', ')}`,`Average reconstruction confidence: ${avg??'—'}%`];summary.forEach((t,i)=>doc.text(t,margin,82+i*18));}doc.save('crochet-geometric-pattern.pdf');}catch(err){console.error(err);alert('Could not create PDF. Please check your connection and try again.');}}
exportPdfBtn?.addEventListener('click',exportPatternPdf);mobileExportPdfBtn?.addEventListener('click',exportPatternPdf);quickExportPdfBtn?.addEventListener('click',exportPatternPdf);window.buildEnglishWrittenPattern=buildEnglishWrittenPattern;window.exportPatternPdf=exportPatternPdf;window.renderCrochetChartCanvas=renderChartCanvas;