// v8.1 — PDF written instructions are compiled from validated Pattern IR.
(()=>{
  const CELL=24;
  function snapshot(){return window.__LACE_LAYOUT_SNAPSHOT;}
  function compiled(){
    const g=window.activeCrochetGraph;
    if(g?.validation?.ok&&window.CrochetInstructionCompiler){try{return window.CrochetInstructionCompiler.compile(g)}catch(e){console.error(e)}}
    return null;
  }
  function currentWritten(){return compiled()?.text||'';}
  function currentParams(){return snapshot()?.params||window.activeCrochetGraph?.params||{middleChain:7,outerChain:11};}
  function enabled(){return typeof window.__CROCHET_CONSTRUCTION_GUIDES_ENABLED==='function'?window.__CROCHET_CONSTRUCTION_GUIDES_ENABLED():true;}
  function visibleNodes(){return (snapshot()?.nodes||[]).filter(n=>!/(^|-)join$/.test(n.role||'')&&n.role!=='r1-join');}
  function scaleSize(){const n=Number(window.__CROCHET_PDF_STITCH_SCALE||window.__CROCHET_STITCH_SCALE||1);return Number.isFinite(n)&&n>0?n:1;}
  function lineScale(){const n=Number(window.__CROCHET_PDF_LINE_WEIGHT_SCALE||window.__CROCHET_LINE_WEIGHT_SCALE||1);return Number.isFinite(n)&&n>0?n:1;}
  function metric(n){return{w:Number(n.visualWidth)||window.CROCHET_STITCH_METRICS?.[n.type]?.visualWidthPx||18,h:Number(n.visualHeight)||window.CROCHET_STITCH_METRICS?.[n.type]?.visualHeightPx||18};}
  function bounds(){const ns=visibleNodes(),f=scaleSize();if(!ns.length)return null;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const n of ns){const m=metric(n),x=n.gridCol*CELL,y=n.gridRow*CELL,w=m.w*f,h=m.h*f;minX=Math.min(minX,x-w/2);maxX=Math.max(maxX,x+w/2);minY=Math.min(minY,y-h/2);maxY=Math.max(maxY,y+h/2);}const pad=90;return{minX:minX-pad,minY:minY-pad,maxX:maxX+pad,maxY:maxY+pad};}
  function line(ctx,x1,y1,x2,y2){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
  function symbol(ctx,type,x,y,size,rotation,stroke){ctx.save();ctx.translate(x,y);ctx.rotate((rotation||0)*Math.PI/180);ctx.strokeStyle='#111';ctx.fillStyle='#111';ctx.lineWidth=stroke;ctx.lineCap='round';ctx.lineJoin='round';const s=size;if(type==='chain'){ctx.beginPath();ctx.ellipse(0,0,s*.34,s*.14,0,0,Math.PI*2);ctx.stroke();}else if(type==='slip'){ctx.beginPath();ctx.arc(0,0,s*.1,0,Math.PI*2);ctx.fill();}else if(type==='single'){line(ctx,-s*.25,-s*.25,s*.25,s*.25);line(ctx,s*.25,-s*.25,-s*.25,s*.25);}else if(type==='half'){line(ctx,0,-s*.4,0,s*.4);line(ctx,-s*.23,-s*.15,s*.23,-s*.15);}else if(type==='double'){line(ctx,0,-s*.42,0,s*.42);line(ctx,-s*.23,-s*.2,s*.23,-s*.2);line(ctx,-s*.2,s*.05,s*.2,-s*.1);}else if(type==='treble'||type==='dtr'){line(ctx,0,-s*.44,0,s*.44);line(ctx,-s*.23,-s*.23,s*.23,-s*.23);const c=type==='dtr'?3:2;for(let k=0;k<c;k++){const yy=-s*.02+k*s*.15;line(ctx,-s*.2,yy+s*.08,s*.2,yy-s*.08);}}else if(type==='ring'){ctx.beginPath();ctx.arc(0,0,s*.3,0,Math.PI*2);ctx.stroke();}ctx.restore();}
  function arrow(ctx,a,b,label,map){const A=map(a),B=map(b);ctx.save();ctx.strokeStyle='#59666f';ctx.fillStyle='#59666f';ctx.lineWidth=2;ctx.setLineDash([8,7]);line(ctx,A.x,A.y,B.x,B.y);ctx.setLineDash([]);const ang=Math.atan2(B.y-A.y,B.x-A.x),q=9;ctx.beginPath();ctx.moveTo(B.x,B.y);ctx.lineTo(B.x-q*Math.cos(ang-.5),B.y-q*Math.sin(ang-.5));ctx.lineTo(B.x-q*Math.cos(ang+.5),B.y-q*Math.sin(ang+.5));ctx.closePath();ctx.fill();if(label){ctx.font='700 13px system-ui';ctx.fillStyle='#34424b';ctx.strokeStyle='white';ctx.lineWidth=4;const x=(A.x+B.x)/2+8,y=(A.y+B.y)/2-8;ctx.strokeText(label,x,y);ctx.fillText(label,x,y);}ctx.restore();}
  function dot(ctx,p,color,map,label,dx=10,dy=-10){const P=map(p);ctx.save();ctx.fillStyle=color;ctx.strokeStyle='white';ctx.lineWidth=3;ctx.beginPath();ctx.arc(P.x,P.y,6,0,Math.PI*2);ctx.fill();ctx.stroke();if(label){ctx.font='800 13px system-ui';ctx.fillStyle=color;ctx.strokeStyle='white';ctx.lineWidth=4;ctx.strokeText(label,P.x+dx,P.y+dy);ctx.fillText(label,P.x+dx,P.y+dy);}ctx.restore();}
  function guideData(){const s=snapshot(),all=s?.nodes||[];const find=(r,sec)=>all.find(n=>n.role===r&&(sec==null||n.sector===sec));const list=(r,sec)=>all.filter(n=>n.role===r&&(sec==null||n.sector===sec));const p=n=>n?{x:n.gridCol*CELL,y:n.gridRow*CELL}:null;const cs=all.filter(n=>n.role==='center-sc');const r3=p(find('inner-petal-stitch-join',5)),r4=p(cs[1]),r5=p(find('mid-petal-stitch-join',5)),r6t=p(find('mid-petal-stitch-join',1)),arc=list('outer-chain',5),r7=arc.length?p(arc[Math.floor(arc.length/2)]):null;return{r3,r4,r5,r6t,r7};}
  function renderChart(){const s=snapshot();if(!s?.validation?.ok)return null;const b=bounds();if(!b)return null;const rawW=b.maxX-b.minX,rawH=b.maxY-b.minY,maxDim=2200,fit=Math.min(1.7,maxDim/Math.max(rawW,rawH)),canvas=document.createElement('canvas');canvas.width=Math.max(520,Math.round(rawW*fit));canvas.height=Math.max(520,Math.round(rawH*fit));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);const map=p=>({x:(p.x-b.minX)*fit,y:(p.y-b.minY)*fit});const sf=scaleSize(),lw=Math.max(.5,1.5*lineScale()*fit);for(const n of visibleNodes()){const p=map({x:n.gridCol*CELL,y:n.gridRow*CELL}),m=metric(n),sz=Math.max(m.w,m.h)*sf*fit;symbol(ctx,n.type,p.x,p.y,sz,n.rotation||0,lw);}if(enabled()){const g=guideData(),p=currentParams();if(g.r3&&g.r4&&g.r5&&g.r6t&&g.r7){dot(ctx,g.r3,'#d64545',map,'R3 end');dot(ctx,g.r4,'#1f9d55',map,'R4 start',10,18);arrow(ctx,g.r3,g.r4,'sl st to next unused R1 sc',map);dot(ctx,g.r5,'#d64545',map,'R5 end / R6 start');arrow(ctx,g.r5,g.r6t,`ch ${p.outerChain} behind work`,map);dot(ctx,g.r7,'#1f9d55',map,`R7 first ch-${p.outerChain} sp`,10,18);arrow(ctx,g.r5,g.r7,`work into first ch-${p.outerChain} sp`,map);}}return canvas;}
  async function exportPdf(){const s=snapshot(),instructions=compiled();if(!s?.validation?.ok||!instructions)return window.exportPatternPdf?.();try{const{jsPDF}=await import('https://cdn.jsdelivr.net/npm/jspdf@2.5.2/+esm'),doc=new jsPDF({unit:'pt',format:'a4'}),W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight(),m=42;doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('Crochet Diagram',m,44);doc.setFont('helvetica','normal');doc.setFontSize(10);doc.text('Validated construction-guided chart',m,61);const c=renderChart();if(c){const maxW=W-m*2,maxH=H-190,fit=Math.min(maxW/c.width,maxH/c.height),w=c.width*fit,h=c.height*fit;doc.addImage(c.toDataURL('image/png'),'PNG',(W-w)/2,78,w,h,undefined,'FAST');}doc.addPage();doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text('Written Pattern · compiled from validated Pattern IR',m,48);doc.setFont('helvetica','normal');doc.setFontSize(10.3);const lines=doc.splitTextToSize(instructions.text,W-m*2);let y=74;for(const t of lines){if(y>H-42){doc.addPage();y=48;}doc.text(t,m,y);y+=13.5;}doc.save('crochet-geometric-pattern.pdf');}catch(e){console.error(e);alert('Could not create PDF. Please check your connection and try again.');}}
  function syncWritten(){const text=currentWritten(),el=document.getElementById('laceWritten');if(el&&el.style.display!=='none'&&text)el.textContent=text;}
  document.addEventListener('click',e=>{if(e.target?.id==='laceGenerate'||e.target?.id==='laceImport')setTimeout(syncWritten,100);if(['exportPdfBtn','mobileExportPdfBtn','quickExportPdfBtn'].includes(e.target?.id)&&snapshot()?.validation?.ok){e.preventDefault();e.stopImmediatePropagation();exportPdf();}},true);
  setTimeout(syncWritten,200);
})();