// Lace Flower Renderer v6.7 — deterministic explicit petal profiles; no runtime search.
(()=>{
const CELL=24,VERSION='v6.7',SIDE=150,CX=75,CY=75,STEP=Math.PI*2/5;
if(typeof render!=='function'||typeof board==='undefined')return;
window.__LACE_RENDERER_VERSION=VERSION;board.dataset.laceRenderer=VERSION;document.title=`Crochet Pattern Designer · ${VERSION}`;
queueMicrotask(()=>{const brand=document.querySelector('.brandcopy strong');if(brand)brand.textContent=`Crochet CAD  ${VERSION}`;const sub=document.querySelector('.brandcopy span');if(sub)sub.textContent='PATTERN DESIGNER';const h=document.querySelector('#photoModeModal .photo-card h2');if(h)h.textContent=`5-PETAL LAYERED LACE FLOWER · ${VERSION}`;});
const JOIN=/join$/,BODY=new Set(['chain','single','half','double','treble','dtr','picot','puff','bobble','cluster','shell']);
const ROLES=['inner-chain','inner-petal-stitch','mid-chain','mid-petal-stitch','outer-chain','outer-petal-stitch','edge-sc'];
const EXPECT={'inner-chain':3,'inner-petal-stitch':7,'mid-chain':7,'mid-petal-stitch':11,'outer-chain':11,'outer-petal-stitch':17,'edge-sc':19};
const CAN={
 'inner-chain':[[-2,5],[0,7],[2,5]],
 'inner-petal-stitch':[[-4,7],[-3,9],[-2,11],[0,13],[2,11],[3,9],[4,7]],
 'mid-chain':[[-5,14],[-4,16],[-3,18],[0,20],[3,18],[4,16],[5,14]],
 'mid-petal-stitch':[[-8,17],[-7,19],[-6,22],[-4,25],[-2,28],[0,31],[2,28],[4,25],[6,22],[7,19],[8,17]],
 'outer-chain':[[-9,31],[-8,33],[-6,35],[-4,37],[-2,39],[0,41],[2,39],[4,37],[6,35],[8,33],[9,31]],
 'outer-petal-stitch':[[-13,35],[-12,37],[-11,40],[-9,43],[-7,46],[-5,49],[-3,52],[-2,55],[0,59],[2,55],[3,52],[5,49],[7,46],[9,43],[11,40],[12,37],[13,35]],
 'edge-sc':[[-15,39],[-14,42],[-13,45],[-11,48],[-9,51],[-7,54],[-5,57],[-3,60],[-2,64],[0,68],[2,64],[3,60],[5,57],[7,54],[9,51],[11,48],[13,45],[14,42],[15,39]]
};
const MET=()=>window.CROCHET_STITCH_METRICS||{};
const roleItems=(g,r,s)=>g.filter(i=>i.role===r&&(s==null||i.sector===s)).sort((a,b)=>(a.orderInPath??0)-(b.orderInPath??0));
const isBody=i=>BODY.has(i?.type)&&!JOIN.test(i?.role||'');
function metric(i){const m=MET()[i.type]||{visualWidthPx:18,visualHeightPx:18};return{w:m.visualWidthPx||18,h:m.visualHeightPx||18};}
function setNode(i,c,r,rot=0){i.gridCol=c;i.gridRow=r;i.gridX=c;i.gridY=r;i.xPx=c*CELL;i.yPx=r*CELL;i.x=(i.xPx/Math.max(board.clientWidth||3600,1))*100;i.y=i.yPx;i.rotation=rot;i.gridCellPx=CELL;i.coordinateSystem='grid-index';const m=metric(i);i.visualWidth=m.w;i.visualHeight=m.h;i.footprint={widthPx:m.w,heightPx:m.h,rotationDeg:rot,body:isBody(i)};if(!Object.prototype.hasOwnProperty.call(i,'workedInto'))i.workedInto=null;}
function localAngle(role,k){const [t,r]=CAN[role][k];return Math.atan2(t,r)*180/Math.PI;}
function sectorPoint(t,r,s){const a=-Math.PI/2+(s-1)*STEP,ux=Math.cos(a),uy=Math.sin(a),tx=-uy,ty=ux;return{x:Math.round(CX+ux*r+tx*t),y:Math.round(CY+uy*r+ty*t)};}
function corners(i){const m=metric(i),hw=m.w/2+1.25,hh=m.h/2+1.25,a=(i.rotation||0)*Math.PI/180,c=Math.cos(a),s=Math.sin(a),cx=i.gridCol*CELL,cy=i.gridRow*CELL;return[[-hw,-hh],[hw,-hh],[hw,hh],[-hw,hh]].map(([x,y])=>({x:cx+x*c-y*s,y:cy+x*s+y*c}));}
function proj(poly,ax){let min=Infinity,max=-Infinity;for(const p of poly){const v=p.x*ax.x+p.y*ax.y;min=Math.min(min,v);max=Math.max(max,v);}return{min,max};}
function overlap(a,b){const pa=corners(a),pb=corners(b),axes=[];for(const poly of [pa,pb])for(let k=0;k<2;k++){const u=poly[k],v=poly[(k+1)%4],dx=v.x-u.x,dy=v.y-u.y,l=Math.hypot(dx,dy)||1;axes.push({x:-dy/l,y:dx/l});}for(const ax of axes){const A=proj(pa,ax),B=proj(pb,ax);if(A.max<=B.min+.25||B.max<=A.min+.25)return false;}return true;}
function bodyCollisions(g){const b=g.filter(isBody),out=[];for(let i=0;i<b.length;i++)for(let j=i+1;j<b.length;j++){if(Math.abs(b[i].gridCol-b[j].gridCol)>5||Math.abs(b[i].gridRow-b[j].gridRow)>5)continue;if(overlap(b[i],b[j]))out.push({a:b[i],b:b[j]});}return out;}
function localBBox(nodes,s){const a=-Math.PI/2+(s-1)*STEP,ux={x:Math.cos(a),y:Math.sin(a)},tx={x:-Math.sin(a),y:Math.cos(a)};let minT=Infinity,maxT=-Infinity,minR=Infinity,maxR=-Infinity;for(const i of nodes)for(const p of corners(i)){const dx=p.x/CELL-CX,dy=p.y/CELL-CY,t=dx*tx.x+dy*tx.y,r=dx*ux.x+dy*ux.y;minT=Math.min(minT,t);maxT=Math.max(maxT,t);minR=Math.min(minR,r);maxR=Math.max(maxR,r);}return{minX:minT,maxX:maxT,minY:minR,maxY:maxR,width:maxT-minT,height:maxR-minR};}
function wholeBBox(nodes){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const i of nodes)for(const p of corners(i)){minX=Math.min(minX,p.x/CELL);maxX=Math.max(maxX,p.x/CELL);minY=Math.min(minY,p.y/CELL);maxY=Math.max(maxY,p.y/CELL);}return{minX,minY,maxX,maxY,width:maxX-minX,height:maxY-minY};}
function symmetry(g){let max=0;const base={};for(const r of ROLES)base[r]=roleItems(g,r,1);for(let s=2;s<=5;s++){const ang=-(s-1)*STEP,c=Math.cos(ang),si=Math.sin(ang);for(const r of ROLES){const a=base[r],b=roleItems(g,r,s);for(let k=0;k<a.length;k++){const x=b[k].gridCol-CX,y=b[k].gridRow-CY,rx=x*c-y*si,ry=x*si+y*c;max=Math.max(max,Math.hypot(rx-(a[k].gridCol-CX),ry-(a[k].gridRow-CY)));}}}return max;}
function placeJoin(i,t){if(!i||!t)return;setNode(i,t.gridCol,t.gridRow,t.rotation||0);i.visualJoin=true;i.footprint.body=false;}
function validate(g){const errors=[],counts=[];for(let s=1;s<=5;s++)counts.push(g.filter(i=>i.sector===s&&!JOIN.test(i.role||'')).length);if(new Set(counts).size>1)errors.push(`sector stitch counts differ: ${counts.join('/')}`);for(const r of ROLES)for(let s=1;s<=5;s++)if(roleItems(g,r,s).length!==EXPECT[r])errors.push(`sector ${s} ${r} count mismatch`);const missing=g.filter(i=>!Number.isInteger(i.gridCol)||!Number.isInteger(i.gridRow));if(missing.length)errors.push(`missing/non-integer grid coordinates: ${missing.length}`);const collisions=bodyCollisions(g);if(collisions.length)errors.push(`body collisions: ${collisions.length}`);const boxes=Array.from({length:5},(_,k)=>localBBox(g.filter(i=>i.sector===k+1&&!JOIN.test(i.role||'')),k+1)),ws=boxes.map(b=>b.width),hs=boxes.map(b=>b.height);if(Math.max(...ws)-Math.min(...ws)>1||Math.max(...hs)-Math.min(...hs)>1)errors.push('sector bbox consistency exceeded 1 grid cell');const sym=symmetry(g);if(sym>1.75)errors.push(`rotational symmetry error ${sym.toFixed(2)} cells exceeds tolerance`);const wb=wholeBBox(g.filter(i=>!JOIN.test(i.role||'')));let clipped=0;for(const i of g.filter(i=>!JOIN.test(i.role||''))){const b=wholeBBox([i]);if(b.minX<0||b.minY<0||b.maxX>SIDE||b.maxY>SIDE)clipped++;}if(clipped)errors.push(`clipped symbols: ${clipped}`);return{ok:!errors.length,errors:[...new Set(errors)],bodyCollisions:collisions.length,collisions,sectorBboxes:boxes,symmetryError:sym,clippedSymbols:clipped,wholeBBox:wb,counts};}
function fail(msg){const r={ok:false,errors:[msg],bodyCollisions:0,collisions:[],sectorBboxes:[],symmetryError:Infinity,clippedSymbols:0,wholeBBox:null,counts:[]};const d={renderer:`lace-flower-renderer-${VERSION}`,bodyCollisions:0,sectorBboxSizes:[],symmetryError:'—',clippedSymbols:0,validation:'FAIL'};window.__LACE_DEBUG_SUMMARY=d;window.__LACE_LAYOUT_SNAPSHOT={renderer:d.renderer,cellPx:CELL,validation:r,debug:d,nodes:[]};return r;}
function layout(list){const g=list.filter(i=>i?.generatedPattern&&i.patternKind==='lace-flower');if(!g.length)return{ok:true,errors:[],bodyCollisions:0,sectorBboxes:[],symmetryError:0,clippedSymbols:0};board.style.width=board.style.minWidth=SIDE*CELL+'px';board.style.height=board.style.minHeight=SIDE*CELL+'px';const center=g.find(i=>i.role==='start');if(!center)return fail('Missing center');setNode(center,CX,CY,0);center.footprint.body=false;const cp=[[0,-4],[2,-3],[4,-1],[4,1],[2,3],[0,4],[-2,3],[-4,1],[-4,-1],[-2,-3]],csc=roleItems(g,'center-sc',null).sort((a,b)=>(a.centerIndex??0)-(b.centerIndex??0));csc.forEach((i,k)=>setNode(i,CX+cp[k][0],CY+cp[k][1],k*36));placeJoin(g.find(i=>i.role==='r1-join'),csc[0]);
for(let s=1;s<=5;s++){const deg=(s-1)*72;for(const r of ROLES){const arr=roleItems(g,r,s),pts=CAN[r];if(arr.length!==pts.length)return fail(`sector ${s} ${r} point count mismatch`);arr.forEach((i,k)=>{const [t,rr]=pts[k],p=sectorPoint(t,rr,s);setNode(i,p.x,p.y,deg+localAngle(r,k));i.canonicalLocal={t,r:rr};i.sectorAngleDeg=deg;});}const even=csc[(s*2)%10],odd=csc[(s*2+1)%10],mp=roleItems(g,'mid-petal-stitch',s),edge=roleItems(g,'edge-sc',s);placeJoin(g.find(i=>i.role==='inner-chain-join'&&i.sector===s),even);placeJoin(g.find(i=>i.role==='inner-petal-stitch-join'&&i.sector===s),even);placeJoin(g.find(i=>i.role==='mid-chain-join'&&i.sector===s),odd);placeJoin(g.find(i=>i.role==='mid-petal-stitch-join'&&i.sector===s),odd);placeJoin(g.find(i=>i.role==='outer-chain-join'&&i.sector===s),mp.at(-1));placeJoin(g.find(i=>i.role==='outer-petal-stitch-join'&&i.sector===s),mp.at(-1));placeJoin(g.find(i=>i.role==='edge-join'&&i.sector===s),edge[0]);}
const result=validate(g),debug={renderer:`lace-flower-renderer-${VERSION}`,bodyCollisions:result.bodyCollisions,sectorBboxSizes:result.sectorBboxes.map(b=>`${b.width.toFixed(1)}x${b.height.toFixed(1)}`),symmetryError:Number.isFinite(result.symmetryError)?+result.symmetryError.toFixed(2):'—',clippedSymbols:result.clippedSymbols,validation:result.ok?'PASS':'FAIL'};window.__LACE_DEBUG_SUMMARY=debug;window.__LACE_LAYOUT_SNAPSHOT={renderer:debug.renderer,createdAt:new Date().toISOString(),cellPx:CELL,center:{gridCol:CX,gridRow:CY},validation:result,debug,nodes:g.map(i=>({id:i.id,type:i.type,role:i.role,sector:i.sector,gridCol:i.gridCol,gridRow:i.gridRow,rotation:i.rotation,workedInto:i.workedInto,visualWidth:i.visualWidth,visualHeight:i.visualHeight,footprint:i.footprint}))};return result;}
function rejection(result){let e=board.querySelector('.lace-layout-rejected');if(result.ok){e?.remove();return;}if(!e){e=document.createElement('div');e.className='lace-layout-rejected';e.style.cssText='position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);z-index:20;padding:18px 22px;max-width:520px;background:#fff3f3;border:2px solid #c62828;border-radius:10px;color:#8b1111;font:600 14px/1.45 system-ui;text-align:center;box-shadow:0 8px 24px rgba(0,0,0,.15)';board.appendChild(e);}e.innerHTML=`<strong style="font-size:18px">LAYOUT REJECTED</strong><br>${result.errors.join('<br>')}`;}
function apply(result){const els=[...board.querySelectorAll('.placed')];items.forEach((i,k)=>{if(!i?.generatedPattern||i.patternKind!=='lace-flower')return;const e=els[k];if(!e)return;if(!result.ok||i.visualJoin){e.style.display='none';return;}e.style.display='grid';e.style.left=`${i.gridCol*CELL}px`;e.style.top=`${i.gridRow*CELL}px`;e.style.width=`${i.visualWidth}px`;e.style.height=`${i.visualHeight}px`;e.style.transform=`translate(-50%,-50%) rotate(${i.rotation||0}deg)`;e.dataset.renderer=VERSION;e.dataset.gridCol=String(i.gridCol);e.dataset.gridRow=String(i.gridRow);const svg=e.querySelector('svg');if(svg){svg.setAttribute('width',i.visualWidth);svg.setAttribute('height',i.visualHeight);svg.style.width=`${i.visualWidth}px`;svg.style.height=`${i.visualHeight}px`;}});rejection(result);}
function fit(result){if(!result.ok||!result.wholeBBox||!boardWrap)return;const b=result.wholeBBox,margin=3,minX=(b.minX-margin)*CELL,maxX=(b.maxX+margin)*CELL,minY=(b.minY-margin)*CELL,maxY=(b.maxY+margin)*CELL,vw=boardWrap.clientWidth||800,vh=boardWrap.clientHeight||600,z=Math.max(.4,Math.min(1.5,Math.min(vw/(maxX-minX),vh/(maxY-minY))));if(typeof applyZoom==='function')applyZoom(z);boardWrap.scrollLeft=Math.max(0,((minX+maxX)/2)*z-vw/2);boardWrap.scrollTop=Math.max(0,((minY+maxY)/2)*z-vh/2);}
const prev=render;render=function(...args){let result={ok:true,errors:[],bodyCollisions:0,sectorBboxes:[],symmetryError:0,clippedSymbols:0};if(Array.isArray(items)&&items.some(i=>i?.patternKind==='lace-flower'))result=layout(items);const out=prev(...args);apply(result);board.dataset.laceFlowerValid=result.ok?'true':'false';board.dataset.laceValidation=result.ok?'PASS':'FAIL';if(result.ok&&items.some(i=>i?.patternKind==='lace-flower'))setTimeout(()=>fit(result),0);return out;};
window.layoutLaceFlowerV67=layout;window.validateLaceFlowerV67=layout;window.fitLaceFlowerV6=fit;
})();