// v8.0 — deterministic parameterized lace renderer. Geometry is generated from topology counts.
(()=>{
const CELL=24,VERSION='v8.0',SIDE=170,CX=85,CY=85,STEP=Math.PI*2/5;
if(typeof render!=='function'||typeof board==='undefined')return;
const BODY=new Set(['chain','single','half','double','treble','dtr','picot','puff','bobble','cluster','shell']);
const ROLES=['inner-chain','inner-petal-stitch','mid-chain','mid-petal-stitch','outer-chain','outer-petal-stitch','edge-sc'];
const MET=()=>window.CROCHET_STITCH_METRICS||{};
const roleItems=(g,r,s)=>g.filter(i=>i.role===r&&(s==null||i.sector===s)).sort((a,b)=>(a.orderInPath??0)-(b.orderInPath??0));
const isJoin=i=>/join$/.test(i?.role||'');const isBody=i=>BODY.has(i?.type)&&!isJoin(i);
function metric(i){const m=MET()[i.type]||{visualWidthPx:18,visualHeightPx:18};return{w:m.visualWidthPx||18,h:m.visualHeightPx||18};}
function setNode(i,c,r,rot=0){i.gridCol=c;i.gridRow=r;i.gridX=c;i.gridY=r;i.xPx=c*CELL;i.yPx=r*CELL;i.x=(i.xPx/Math.max(board.clientWidth||4080,1))*100;i.y=i.yPx;i.rotation=rot;i.gridCellPx=CELL;i.coordinateSystem='grid-index';const m=metric(i);i.visualWidth=m.w;i.visualHeight=m.h;i.footprint={widthPx:m.w,heightPx:m.h,rotationDeg:rot,body:isBody(i)};}
function profile(count,halfW,baseR,tipR){const out=[];if(count<=1)return[[0,tipR]];for(let k=0;k<count;k++){const u=k/(count-1),t=-halfW+2*halfW*u,r=baseR+(tipR-baseR)*Math.sin(Math.PI*u);out.push([t,r]);}return out;}
function roleProfile(role,count,p,spread=1){const minHalf=(count-1)*.82*spread;if(role==='inner-chain')return profile(count,Math.max(2.2,minHalf),5,7.5);if(role==='inner-petal-stitch')return profile(count,Math.max(4.2,minHalf),7,13.5+(count-7)*.9*spread);if(role==='mid-chain')return profile(count,Math.max(5.2,minHalf),14,20+(p.middleChain-7)*.9*spread);if(role==='mid-petal-stitch')return profile(count,Math.max(8,minHalf),17,31);if(role==='outer-chain')return profile(count,Math.max(9.5,minHalf),31,41+(p.outerChain-11)*1.05*spread);if(role==='outer-petal-stitch')return profile(count,Math.max(13,minHalf),35,59);if(role==='edge-sc')return profile(count,Math.max(15,minHalf),39,68);return profile(count,Math.max(4,minHalf),8,12)}
function sectorPoint(t,r,s){const a=-Math.PI/2+(s-1)*STEP,ux=Math.cos(a),uy=Math.sin(a),tx=-uy,ty=ux;return{x:Math.round(CX+ux*r+tx*t),y:Math.round(CY+uy*r+ty*t)}}
function localAngle(pt){return Math.atan2(pt[0],pt[1])*180/Math.PI;}
function corners(i){const m=metric(i),hw=m.w/2+1,hh=m.h/2+1,a=(i.rotation||0)*Math.PI/180,c=Math.cos(a),s=Math.sin(a),cx=i.gridCol*CELL,cy=i.gridRow*CELL;return[[-hw,-hh],[hw,-hh],[hw,hh],[-hw,hh]].map(([x,y])=>({x:cx+x*c-y*s,y:cy+x*s+y*c}));}
function proj(poly,ax){let min=Infinity,max=-Infinity;for(const p of poly){const v=p.x*ax.x+p.y*ax.y;min=Math.min(min,v);max=Math.max(max,v)}return{min,max}}
function overlap(a,b){const pa=corners(a),pb=corners(b),axes=[];for(const poly of [pa,pb])for(let k=0;k<2;k++){const u=poly[k],v=poly[(k+1)%4],dx=v.x-u.x,dy=v.y-u.y,l=Math.hypot(dx,dy)||1;axes.push({x:-dy/l,y:dx/l})}for(const ax of axes){const A=proj(pa,ax),B=proj(pb,ax);if(A.max<=B.min+.2||B.max<=A.min+.2)return false}return true}
function bodyCollisions(g){const b=g.filter(isBody),out=[];for(let i=0;i<b.length;i++)for(let j=i+1;j<b.length;j++){if(Math.abs(b[i].gridCol-b[j].gridCol)>6||Math.abs(b[i].gridRow-b[j].gridRow)>6)continue;if(overlap(b[i],b[j]))out.push({a:b[i],b:b[j]})}return out}
function wholeBBox(nodes){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const i of nodes)for(const p of corners(i)){minX=Math.min(minX,p.x/CELL);maxX=Math.max(maxX,p.x/CELL);minY=Math.min(minY,p.y/CELL);maxY=Math.max(maxY,p.y/CELL)}return{minX,minY,maxX,maxY,width:maxX-minX,height:maxY-minY}}
function placeJoin(i,t){if(!i||!t)return;setNode(i,t.gridCol,t.gridRow,t.rotation||0);i.visualJoin=true;i.footprint.body=false;}
function layout(list){const g=list.filter(i=>i?.generatedPattern&&i.patternKind==='lace-flower');if(!g.length)return{ok:true,errors:[],bodyCollisions:0,sectorBboxes:[],symmetryError:0,clippedSymbols:0};const p=window.activeCrochetGraph?.params||{innerDc:3,middleChain:7,outerChain:11};board.style.width=board.style.minWidth=SIDE*CELL+'px';board.style.height=board.style.minHeight=SIDE*CELL+'px';const center=g.find(i=>i.role==='start');if(!center)return{ok:false,errors:['Missing center']};setNode(center,CX,CY,0);center.footprint.body=false;const cp=[[0,-4],[2,-3],[4,-1],[4,1],[2,3],[0,4],[-2,3],[-4,1],[-4,-1],[-2,-3]],csc=roleItems(g,'center-sc',null).sort((a,b)=>(a.centerIndex??0)-(b.centerIndex??0));csc.forEach((i,k)=>setNode(i,CX+cp[k][0],CY+cp[k][1],k*36));placeJoin(g.find(i=>i.role==='r1-join'),csc[0]);
let spread=1,collisions=[];for(let attempt=0;attempt<9;attempt++,spread+=.09){for(let s=1;s<=5;s++){const deg=(s-1)*72;for(const r of ROLES){const arr=roleItems(g,r,s),pts=roleProfile(r,arr.length,p,spread);arr.forEach((i,k)=>{const q=sectorPoint(pts[k][0],pts[k][1],s);setNode(i,q.x,q.y,deg+localAngle(pts[k]));i.canonicalLocal={t:pts[k][0],r:pts[k][1]};i.sectorAngleDeg=deg;})}}collisions=bodyCollisions(g);if(!collisions.length)break}
for(let s=1;s<=5;s++){const even=csc[(s*2)%10],odd=csc[(s*2+1)%10],mp=roleItems(g,'mid-petal-stitch',s),edge=roleItems(g,'edge-sc',s);placeJoin(g.find(i=>i.role==='inner-chain-join'&&i.sector===s),even);placeJoin(g.find(i=>i.role==='inner-petal-stitch-join'&&i.sector===s),even);placeJoin(g.find(i=>i.role==='mid-chain-join'&&i.sector===s),odd);placeJoin(g.find(i=>i.role==='mid-petal-stitch-join'&&i.sector===s),odd);placeJoin(g.find(i=>i.role==='outer-chain-join'&&i.sector===s),mp.at(-1));placeJoin(g.find(i=>i.role==='outer-petal-stitch-join'&&i.sector===s),mp.at(-1));placeJoin(g.find(i=>i.role==='edge-join'&&i.sector===s),edge[0]);}
const transition=g.find(i=>i.role==='r4-transition-join');if(transition)placeJoin(transition,csc[1]);
const missing=g.filter(i=>!Number.isInteger(i.gridCol)||!Number.isInteger(i.gridRow));collisions=bodyCollisions(g);const wb=wholeBBox(g.filter(i=>!isJoin(i)));let clipped=0;for(const i of g.filter(i=>!isJoin(i))){const b=wholeBBox([i]);if(b.minX<0||b.minY<0||b.maxX>SIDE||b.maxY>SIDE)clipped++}const errors=[];if(missing.length)errors.push(`missing/non-integer grid coordinates: ${missing.length}`);if(collisions.length)errors.push(`body collisions: ${collisions.length}`);if(clipped)errors.push(`clipped symbols: ${clipped}`);const result={ok:!errors.length,errors,bodyCollisions:collisions.length,collisions,sectorBboxes:[],symmetryError:0,clippedSymbols:clipped,wholeBBox:wb,layoutSpread:spread};window.__LACE_LAYOUT_SNAPSHOT={renderer:`lace-flower-renderer-${VERSION}`,createdAt:new Date().toISOString(),cellPx:CELL,center:{gridCol:CX,gridRow:CY},params:{...p},validation:result,debug:{renderer:`lace-flower-renderer-${VERSION}`,bodyCollisions:result.bodyCollisions,sectorBboxSizes:[],symmetryError:0,clippedSymbols:clipped,validation:result.ok?'PASS':'FAIL'},nodes:g.map(i=>({id:i.id,type:i.type,role:i.role,sector:i.sector,gridCol:i.gridCol,gridRow:i.gridRow,rotation:i.rotation,workedInto:i.workedInto,anchor:i.anchor,visualWidth:i.visualWidth,visualHeight:i.visualHeight,footprint:i.footprint}))};return result;}
function apply(result){const els=[...board.querySelectorAll('.placed')];items.forEach((i,k)=>{if(!i?.generatedPattern||i.patternKind!=='lace-flower')return;const e=els[k];if(!e)return;if(!result.ok||i.visualJoin){e.style.display='none';return}e.style.display='grid';e.style.left=`${i.gridCol*CELL}px`;e.style.top=`${i.gridRow*CELL}px`;e.style.width=`${i.visualWidth}px`;e.style.height=`${i.visualHeight}px`;e.style.transform=`translate(-50%,-50%) rotate(${i.rotation||0}deg)`;e.dataset.renderer=VERSION;e.dataset.gridCol=String(i.gridCol);e.dataset.gridRow=String(i.gridRow);const svg=e.querySelector('svg');if(svg){svg.setAttribute('width',i.visualWidth);svg.setAttribute('height',i.visualHeight);svg.setAttribute('stroke','#050505');svg.style.width=`${i.visualWidth}px`;svg.style.height=`${i.visualHeight}px`;svg.style.opacity='1';}})}
function fit(result){if(!result.ok||!result.wholeBBox||!boardWrap)return;const b=result.wholeBBox,margin=3,minX=(b.minX-margin)*CELL,maxX=(b.maxX+margin)*CELL,minY=(b.minY-margin)*CELL,maxY=(b.maxY+margin)*CELL,vw=boardWrap.clientWidth||800,vh=boardWrap.clientHeight||600,fitZoom=Math.max(.3,Math.min(1.5,Math.min(vw/(maxX-minX),vh/(maxY-minY)))),z=Math.max(1,fitZoom);if(typeof applyZoom==='function')applyZoom(z);boardWrap.scrollLeft=Math.max(0,((minX+maxX)/2)*z-vw/2);boardWrap.scrollTop=Math.max(0,((minY+maxY)/2)*z-vh/2)}
const prev=render;render=function(...args){let result={ok:true,errors:[],bodyCollisions:0,wholeBBox:null};if(Array.isArray(items)&&items.some(i=>i?.patternKind==='lace-flower'))result=layout(items);const out=prev(...args);apply(result);board.dataset.laceFlowerValid=result.ok?'true':'false';board.dataset.laceValidation=result.ok?'PASS':'FAIL';if(result.ok)setTimeout(()=>fit(result),20);return out};
window.fitLaceFlowerV8=()=>{const v=window.__LACE_LAYOUT_SNAPSHOT?.validation;if(v)fit(v)};
})();