// v9.0 — deterministic readable 5-petal chart layout. No auto-shrink; fixed radial bands prevent cross-layer overlap.
(()=>{
const CELL=24,VERSION='v9.0',SIDE=240,CX=120,CY=120,STEP=Math.PI*2/5;
if(typeof render!=='function'||typeof board==='undefined')return;
const BODY=new Set(['chain','single','half','double','treble','dtr','picot','puff','bobble','cluster','shell']);
const ROLES=['inner-chain','inner-petal-stitch','mid-chain','mid-petal-stitch','outer-chain','outer-petal-stitch','edge-sc'];
const MET=()=>window.CROCHET_STITCH_METRICS||{};
const POLICY=()=>window.CROCHET_COLLISION_POLICY||null;
const roleItems=(g,r,s)=>g.filter(i=>i.role===r&&(s==null||i.sector===s)).sort((a,b)=>(a.orderInPath??0)-(b.orderInPath??0));
const isJoin=i=>/join$/.test(i?.role||'');const isBody=i=>BODY.has(i?.type)&&!isJoin(i);
function metric(i){const m=MET()[i.type]||{visualWidthPx:30,visualHeightPx:30};return{w:m.visualWidthPx||30,h:m.visualHeightPx||30};}
function setNode(i,c,r,rot=0){i.gridCol=Math.round(c);i.gridRow=Math.round(r);i.gridX=i.gridCol;i.gridY=i.gridRow;i.xPx=i.gridCol*CELL;i.yPx=i.gridRow*CELL;i.x=(i.xPx/(SIDE*CELL))*100;i.y=i.yPx;i.rotation=rot;i.gridCellPx=CELL;i.coordinateSystem='grid-index';const m=metric(i);i.visualWidth=m.w;i.visualHeight=m.h;i.footprint={widthPx:m.w,heightPx:m.h,rotationDeg:rot,body:isBody(i)};}
function profile(count,half,baseR,tipR){const out=[];if(count<=1)return[[0,tipR]];for(let k=0;k<count;k++){const u=k/(count-1),t=-half+2*half*u,r=baseR+(tipR-baseR)*Math.sin(Math.PI*u);out.push([t,r])}return out;}
function roleProfile(role,count){const half=Math.max(2,(count-1)*1.2);if(role==='inner-chain')return profile(count,half,12,16);if(role==='inner-petal-stitch')return profile(count,half,22,30);if(role==='mid-chain')return profile(count,half,35,40);if(role==='mid-petal-stitch')return profile(count,half,46,55);if(role==='outer-chain')return profile(count,half,62,68);if(role==='outer-petal-stitch')return profile(count,half,76,86);if(role==='edge-sc')return profile(count,half,94,102);return profile(count,half,12,18)}
function sectorPoint(t,r,s){const a=-Math.PI/2+(s-1)*STEP,ux=Math.cos(a),uy=Math.sin(a),tx=-uy,ty=ux;return{x:CX+ux*r+tx*t,y:CY+uy*r+ty*t}}
function localAngle(pt){return Math.atan2(pt[0],pt[1])*180/Math.PI;}
function corners(i){const m=metric(i),hw=m.w/2+2,hh=m.h/2+2,a=(i.rotation||0)*Math.PI/180,c=Math.cos(a),s=Math.sin(a),cx=i.gridCol*CELL,cy=i.gridRow*CELL;return[[-hw,-hh],[hw,-hh],[hw,hh],[-hw,hh]].map(([x,y])=>({x:cx+x*c-y*s,y:cy+x*s+y*c}));}
function proj(poly,ax){let min=Infinity,max=-Infinity;for(const p of poly){const v=p.x*ax.x+p.y*ax.y;min=Math.min(min,v);max=Math.max(max,v)}return{min,max}}
function overlap(a,b){const pa=corners(a),pb=corners(b),axes=[];for(const poly of [pa,pb])for(let k=0;k<2;k++){const u=poly[k],v=poly[(k+1)%4],dx=v.x-u.x,dy=v.y-u.y,l=Math.hypot(dx,dy)||1;axes.push({x:-dy/l,y:dx/l})}for(const ax of axes){const A=proj(pa,ax),B=proj(pb,ax);if(A.max<=B.min+.2||B.max<=A.min+.2)return false}return true}
function fallbackIntentional(a,b){return !!a?.workedInto&&a.workedInto===b?.workedInto&&a.role===b?.role&&a.sector===b?.sector&&a.sourceRegion===b?.sourceRegion;}
function classify(a,b,ov){const p=POLICY();if(p?.classifyPair)return p.classifyPair(a,b,ov);if(!ov)return{kind:'separate',invalid:false};if(fallbackIntentional(a,b))return{kind:'shared-target-contact',invalid:false};return{kind:'invalid-body-overlap',invalid:true};}
function diag(a,b,kind){const pick=n=>({id:n?.id||null,type:n?.type||null,role:n?.role||null,sector:n?.sector??null,sourceRegion:n?.sourceRegion||null,workedInto:n?.workedInto||null,gridCol:n?.gridCol??null,gridRow:n?.gridRow??null});return{kind,a:pick(a),b:pick(b)}}
function scan(g){const b=g.filter(isBody),invalid=[],shared=[];for(let i=0;i<b.length;i++)for(let j=i+1;j<b.length;j++){if(Math.abs(b[i].gridCol-b[j].gridCol)>8||Math.abs(b[i].gridRow-b[j].gridRow)>8)continue;const ov=overlap(b[i],b[j]),c=classify(b[i],b[j],ov);if(c.kind==='shared-target-contact')shared.push(diag(b[i],b[j],c.kind));else if(c.invalid)invalid.push(diag(b[i],b[j],c.kind));}return{invalid,shared}}
function bbox(nodes){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const i of nodes)for(const p of corners(i)){minX=Math.min(minX,p.x/CELL);maxX=Math.max(maxX,p.x/CELL);minY=Math.min(minY,p.y/CELL);maxY=Math.max(maxY,p.y/CELL)}return{minX,minY,maxX,maxY,width:maxX-minX,height:maxY-minY}}
function placeJoin(i,t){if(!i||!t)return;setNode(i,t.gridCol,t.gridRow,t.rotation||0);i.visualJoin=true;i.footprint.body=false;}
function layout(list){const g=list.filter(i=>i?.generatedPattern&&i.patternKind==='lace-flower');if(!g.length)return{ok:true,errors:[],bodyCollisions:0,clippedSymbols:0,wholeBBox:null};board.style.width=board.style.minWidth=SIDE*CELL+'px';board.style.height=board.style.minHeight=SIDE*CELL+'px';const center=g.find(i=>i.role==='start');if(!center)return{ok:false,errors:['Missing center'],bodyCollisions:0,clippedSymbols:0};setNode(center,CX,CY,0);center.footprint.body=false;
 const csc=roleItems(g,'center-sc',null).sort((a,b)=>(a.centerIndex??0)-(b.centerIndex??0));csc.forEach((i,k)=>{const a=-Math.PI/2+k*Math.PI*2/10;setNode(i,CX+Math.cos(a)*7,CY+Math.sin(a)*7,k*36)});placeJoin(g.find(i=>i.role==='r1-join'),csc[0]);
 for(let s=1;s<=5;s++){const deg=(s-1)*72;for(const r of ROLES){const arr=roleItems(g,r,s),pts=roleProfile(r,arr.length);arr.forEach((i,k)=>{const q=sectorPoint(pts[k][0],pts[k][1],s);setNode(i,q.x,q.y,deg+localAngle(pts[k]));i.canonicalLocal={t:pts[k][0],r:pts[k][1]};i.sectorAngleDeg=deg;})}}
 for(let s=1;s<=5;s++){const even=csc[(s*2)%10],odd=csc[(s*2+1)%10],mp=roleItems(g,'mid-petal-stitch',s),edge=roleItems(g,'edge-sc',s);placeJoin(g.find(i=>i.role==='inner-chain-join'&&i.sector===s),even);placeJoin(g.find(i=>i.role==='inner-petal-stitch-join'&&i.sector===s),even);placeJoin(g.find(i=>i.role==='mid-chain-join'&&i.sector===s),odd);placeJoin(g.find(i=>i.role==='mid-petal-stitch-join'&&i.sector===s),odd);placeJoin(g.find(i=>i.role==='outer-chain-join'&&i.sector===s),mp.at(-1));placeJoin(g.find(i=>i.role==='outer-petal-stitch-join'&&i.sector===s),mp.at(-1));placeJoin(g.find(i=>i.role==='edge-join'&&i.sector===s),edge[0]);}
 const transition=g.find(i=>i.role==='r4-transition-join');if(transition)placeJoin(transition,csc[1]);const missing=g.filter(i=>!Number.isInteger(i.gridCol)||!Number.isInteger(i.gridRow)),cs=scan(g),wb=bbox(g.filter(i=>!isJoin(i)));let clipped=0;for(const i of g.filter(i=>!isJoin(i))){const b=bbox([i]);if(b.minX<0||b.minY<0||b.maxX>SIDE||b.maxY>SIDE)clipped++}const errors=[];if(missing.length)errors.push(`missing/non-integer grid coordinates: ${missing.length}`);if(cs.invalid.length)errors.push(`invalid body collisions: ${cs.invalid.length}`);if(clipped)errors.push(`clipped symbols: ${clipped}`);const result={ok:!errors.length,errors,bodyCollisions:cs.invalid.length,sharedTargetContacts:cs.shared.length,collisionDiagnostics:cs.invalid,sharedTargetDiagnostics:cs.shared,clippedSymbols:clipped,wholeBBox:wb,layoutSpread:1};window.__LACE_LAYOUT_SNAPSHOT={renderer:`lace-flower-renderer-${VERSION}`,createdAt:new Date().toISOString(),cellPx:CELL,center:{gridCol:CX,gridRow:CY},validation:result,nodes:g.map(i=>({id:i.id,type:i.type,role:i.role,sector:i.sector,gridCol:i.gridCol,gridRow:i.gridRow,rotation:i.rotation,workedInto:i.workedInto,anchor:i.anchor,visualWidth:i.visualWidth,visualHeight:i.visualHeight}))};return result;}
function apply(result){const els=[...board.querySelectorAll('.placed')];items.forEach((i,k)=>{if(!i?.generatedPattern||i.patternKind!=='lace-flower')return;const e=els[k];if(!e)return;if(i.visualJoin){e.style.display='none';return}e.style.display='grid';e.style.left=`${i.gridCol*CELL}px`;e.style.top=`${i.gridRow*CELL}px`;e.style.width=`${i.visualWidth}px`;e.style.height=`${i.visualHeight}px`;e.style.transform=`translate(-50%,-50%) rotate(${i.rotation||0}deg)`;e.dataset.renderer=VERSION;const svg=e.querySelector('svg');if(svg){svg.setAttribute('width',i.visualWidth);svg.setAttribute('height',i.visualHeight);svg.setAttribute('stroke',result.ok?'#050505':'#b42318');svg.style.width=`${i.visualWidth}px`;svg.style.height=`${i.visualHeight}px`;svg.style.opacity='1';}})}
function centerView(result){if(!result.wholeBBox||!boardWrap)return;if(typeof applyZoom==='function')applyZoom(1);const b=result.wholeBBox,cx=((b.minX+b.maxX)/2)*CELL,cy=((b.minY+b.maxY)/2)*CELL;setTimeout(()=>{boardWrap.scrollLeft=Math.max(0,cx-(boardWrap.clientWidth||800)/2);boardWrap.scrollTop=Math.max(0,cy-(boardWrap.clientHeight||600)/2)},0)}
const prev=render;render=function(...args){let result={ok:true,errors:[],bodyCollisions:0,clippedSymbols:0,wholeBBox:null};if(Array.isArray(items)&&items.some(i=>i?.patternKind==='lace-flower'))result=layout(items);const out=prev(...args);apply(result);board.dataset.laceFlowerValid=result.ok?'true':'false';board.dataset.laceValidation=result.ok?'PASS':'FAIL';if(result.wholeBBox)centerView(result);return out};
window.fitLaceFlowerV8=()=>{const v=window.__LACE_LAYOUT_SNAPSHOT?.validation;if(v)centerView(v)};
})();
