// v7.1 Pattern sizing — target-based physical ruler + material inputs before generate.
(()=>{
  const VERSION='v7.1',CELL=24;
  const KEY='crochetCad.patternSizingV71';
  const saved=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}})();
  const state={yarn:saved.yarn||'DK / Light 3',hook:Number(saved.hook)||3.5,targetW:Number(saved.targetW)||20,targetH:Number(saved.targetH)||20,scale:Number(saved.scale)||1};
  function persist(){localStorage.setItem(KEY,JSON.stringify(state));window.__CROCHET_MATERIAL_SETTINGS={...state,mode:'target-size-estimate'};}
  function stamp(){document.title=`Crochet Pattern Designer · ${VERSION}`;const b=document.querySelector('.brandcopy strong');if(b)b.textContent=`Crochet CAD  ${VERSION}`;const h=document.querySelector('#photoModeModal .photo-card h2');if(h&&h.textContent.includes('5-PETAL'))h.textContent=`5-PETAL LAYERED LACE FLOWER · ${VERSION}`;if(window.__LACE_DEBUG_SUMMARY)window.__LACE_DEBUG_SUMMARY.renderer=`lace-flower-renderer-${VERSION}`;}
  function bbox(){const b=window.__LACE_LAYOUT_SNAPSHOT?.validation?.wholeBBox;if(b&&Number.isFinite(b.width)&&Number.isFinite(b.height))return b;if(!Array.isArray(window.items))return null;const p=items.filter(i=>Number.isInteger(i.gridCol)&&Number.isInteger(i.gridRow)&&!i.visualJoin);if(!p.length)return null;const xs=p.map(i=>i.gridCol),ys=p.map(i=>i.gridRow);return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys),width:Math.max(...xs)-Math.min(...xs),height:Math.max(...ys)-Math.min(...ys)};}
  function physical(){const b=bbox();if(!b)return null;const cmPerCell=Math.min(state.targetW/b.width,state.targetH/b.height);return{b,cmPerCell,w:b.width*cmPerCell,h:b.height*cmPerCell};}
  function css(){if(document.getElementById('sizingV71Style'))return;const s=document.createElement('style');s.id='sizingV71Style';s.textContent=`
    #gridToolsV70,.grid-ruler-top-v70,.grid-ruler-left-v70{display:none!important}
    .sizing-v71{position:absolute;right:14px;top:14px;z-index:45;width:288px;padding:12px;border:1px solid #3d4a53;border-radius:10px;background:rgba(18,24,29,.95);color:#f5f7f9;font:12px/1.35 system-ui;box-shadow:0 7px 24px rgba(0,0,0,.26)}
    .sizing-v71 strong{letter-spacing:.03em}.sizing-row{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;margin-top:8px}.sizing-v71 input,.sizing-v71 select{background:#0d1317;color:#fff;border:1px solid #46535e;border-radius:6px;padding:5px 6px}.sizing-v71 input[type=number]{width:65px}.sizing-v71 input[type=range]{grid-column:1/-1;width:100%}.sizing-size{margin-top:9px;padding-top:8px;border-top:1px solid #33414a;font-weight:800;color:#8fe7ff}.sizing-note{margin-top:5px;font-size:10px;color:#aeb8c0}
    #board .ruler-v71{position:absolute;z-index:20;pointer-events:none;color:#26343c;font:9px/1 system-ui}.ruler-v71.top{height:22px;border-bottom:1px solid #768690}.ruler-v71.left{width:28px;border-right:1px solid #768690}.ruler-v71 .tick{position:absolute;background:#768690}.ruler-v71.top .tick{bottom:0;width:1px;height:6px}.ruler-v71.left .tick{right:0;height:1px;width:6px}.ruler-v71 .lbl{position:absolute;white-space:nowrap;font-weight:700;background:rgba(255,255,255,.85);padding:1px 2px;border-radius:2px}.ruler-v71.top .lbl{top:2px;transform:translateX(-50%)}.ruler-v71.left .lbl{left:2px;transform:translateY(-50%)}
    .generator-size-v71{margin:10px 0 12px;padding:10px;border:1px solid #36444e;border-radius:8px;background:#11181d;display:grid;grid-template-columns:1fr 1fr;gap:8px 10px;font:12px/1.3 system-ui}.generator-size-v71 label{display:grid;gap:4px;color:#cbd5db}.generator-size-v71 input,.generator-size-v71 select{background:#0b1014;color:#fff;border:1px solid #46535e;border-radius:6px;padding:6px}.generator-size-v71 .wide{grid-column:1/-1}.generator-size-v71 small{grid-column:1/-1;color:#99a7b0}
  `;document.head.appendChild(s);}
  function applyScale(){if(!window.board||!Array.isArray(window.items))return;const els=[...board.querySelectorAll('.placed')];items.forEach((it,k)=>{if(!it?.generatedPattern||it.patternKind!=='lace-flower'||it.visualJoin)return;const e=els[k];if(!e)return;e.style.transformOrigin='50% 50%';e.style.transform=`translate(-50%,-50%) rotate(${Number(it.rotation)||0}deg) scale(${state.scale})`;});const v=document.getElementById('scaleValV71');if(v)v.textContent=`${Math.round(state.scale*100)}%`;}
  function drawRuler(){if(!window.board)return;board.querySelectorAll('.ruler-v71').forEach(n=>n.remove());const p=physical();if(!p)return;const {b,cmPerCell,w,h}=p;const top=document.createElement('div'),left=document.createElement('div');top.className='ruler-v71 top';left.className='ruler-v71 left';top.style.left=`${b.minX*CELL}px`;top.style.top=`${Math.max(0,b.minY*CELL-24)}px`;top.style.width=`${b.width*CELL}px`;left.style.left=`${Math.max(0,b.minX*CELL-30)}px`;left.style.top=`${b.minY*CELL}px`;left.style.height=`${b.height*CELL}px`;
    const step=w<=25?5:10;for(let cm=0;cm<=w+.01;cm+=step){const x=(cm/cmPerCell)*CELL;const t=document.createElement('i'),l=document.createElement('span');t.className='tick';t.style.left=x+'px';l.className='lbl';l.style.left=x+'px';l.textContent=`${cm} cm`;top.append(t,l);}if(Math.abs((Math.floor(w/step)*step)-w)>0.5){const x=b.width*CELL,t=document.createElement('i'),l=document.createElement('span');t.className='tick';t.style.left=x+'px';l.className='lbl';l.style.left=x+'px';l.textContent=`${w.toFixed(1)} cm`;top.append(t,l);}
    const stepY=h<=25?5:10;for(let cm=0;cm<=h+.01;cm+=stepY){const y=(cm/cmPerCell)*CELL;const t=document.createElement('i'),l=document.createElement('span');t.className='tick';t.style.top=y+'px';l.className='lbl';l.style.top=y+'px';l.textContent=`${cm}`;left.append(t,l);}board.append(top,left);
  }
  function updateText(){const p=physical(),el=document.getElementById('patternSizeV71');if(!el)return;if(!p){el.textContent=`Target: ${state.targetW} × ${state.targetH} cm · generate pattern to measure`;return;}el.textContent=`Estimated finished size: ${p.w.toFixed(1)} × ${p.h.toFixed(1)} cm`;}
  function panel(){if(!window.boardWrap)return;document.getElementById('sizingToolsV71')?.remove();const p=document.createElement('div');p.id='sizingToolsV71';p.className='sizing-v71';p.innerHTML=`<strong>SIZE / GRID · ${VERSION}</strong><div class="sizing-row"><span>Stitch scale</span><b id="scaleValV71">${Math.round(state.scale*100)}%</b><input id="scaleV71" type="range" min="50" max="250" step="5" value="${Math.round(state.scale*100)}"></div><div class="sizing-row"><label>Target width</label><span><input id="targetWV71" type="number" min="5" max="200" step="1" value="${state.targetW}"> cm</span></div><div class="sizing-row"><label>Target height</label><span><input id="targetHV71" type="number" min="5" max="200" step="1" value="${state.targetH}"> cm</span></div><div class="sizing-size" id="patternSizeV71"></div><div class="sizing-note">The ruler measures the pattern bounding box, not the whole whiteboard. Target size is an estimate until real crochet gauge is measured.</div>`;boardWrap.appendChild(p);p.querySelector('#scaleV71').oninput=e=>{state.scale=Number(e.target.value)/100;persist();applyScale()};for(const [id,key] of [['targetWV71','targetW'],['targetHV71','targetH']])p.querySelector('#'+id).oninput=e=>{const v=Number(e.target.value);if(v>0){state[key]=v;persist();drawRuler();updateText();syncGenerator();}};updateText();}
  function generator(){const card=document.querySelector('#photoModeModal .photo-card');if(!card)return;let box=document.getElementById('generatorSizeV71');if(!box){box=document.createElement('div');box.id='generatorSizeV71';box.className='generator-size-v71';const btn=document.getElementById('laceGenerate');if(btn)btn.before(box);else card.appendChild(box);}box.innerHTML=`<label class="wide">Yarn<select id="yarnV71"><option>Fingering / Super Fine 1</option><option>Sport / Fine 2</option><option>DK / Light 3</option><option>Worsted / Medium 4</option><option>Bulky 5</option></select></label><label>Hook<input id="hookV71" type="number" min="1" max="12" step="0.25" value="${state.hook}"></label><label>Target size<input id="genTargetV71" type="number" min="5" max="200" step="1" value="${state.targetW}"></label><small>Default target: 20 × 20 cm. Yarn and hook are saved with the pattern; finished size remains an estimate until you enter a real gauge in a later calibration step.</small>`;box.querySelector('#yarnV71').value=state.yarn;box.querySelector('#yarnV71').onchange=e=>{state.yarn=e.target.value;persist()};box.querySelector('#hookV71').oninput=e=>{state.hook=Number(e.target.value)||3.5;persist()};box.querySelector('#genTargetV71').oninput=e=>{const v=Number(e.target.value);if(v>0){state.targetW=state.targetH=v;persist();const w=document.getElementById('targetWV71'),h=document.getElementById('targetHV71');if(w)w.value=v;if(h)h.value=v;drawRuler();updateText();}};}
  function syncGenerator(){const g=document.getElementById('genTargetV71');if(g&&state.targetW===state.targetH)g.value=state.targetW;}
  function refresh(){stamp();css();generator();panel();applyScale();drawRuler();updateText();persist();}
  const oldRender=window.render;if(typeof oldRender==='function')window.render=function(...args){const out=oldRender.apply(this,args);setTimeout(refresh,0);return out;};document.addEventListener('click',e=>{if(['photoModeBtn','mobilePhotoModeBtn','laceGenerate'].includes(e.target?.id))setTimeout(generator,0)},true);window.addEventListener('resize',()=>setTimeout(drawRuler,80));setTimeout(refresh,0);
})();