// v8.0 — stitch size + line weight UI.
(()=>{
  const VERSION='v8.0',KEY='crochetCad.stitchStyleV76';let state={sizePct:100,linePct:100};try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');if(Number.isFinite(Number(s.sizePct)))state.sizePct=Math.max(1,Math.round(Number(s.sizePct)));if(Number.isFinite(Number(s.linePct)))state.linePct=Math.max(1,Math.round(Number(s.linePct)));}catch{}
  const positive=(v,f)=>{const n=Math.round(Number(v));return Number.isFinite(n)&&n>0?n:f};function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}window.__CROCHET_STITCH_SCALE=state.sizePct/100;window.__CROCHET_PDF_STITCH_SCALE=state.sizePct/100;window.__CROCHET_LINE_WEIGHT_SCALE=state.linePct/100;window.__CROCHET_PDF_LINE_WEIGHT_SCALE=state.linePct/100}
  function stamp(){window.__CROCHET_CAD_VERSION=VERSION;document.title=`Crochet Pattern Designer · ${VERSION}`;const b=document.querySelector('.brandcopy strong');if(b)b.textContent=`Crochet CAD ${VERSION}`;const p=document.querySelector('#sizingToolsV71 > strong');if(p)p.textContent=`SIZE / GRID · ${VERSION}`}
  function css(){if(document.getElementById('stitchPerfV80Style'))return;const s=document.createElement('style');s.id='stitchPerfV80Style';s.textContent=`#board{--crochet-stitch-scale:1;--crochet-line-width:1.5px}#board .placed[data-renderer] svg{transform:scale(var(--crochet-stitch-scale))!important;transform-origin:50% 50%!important;transform-box:fill-box!important;overflow:visible!important;filter:none!important}#board .placed[data-renderer] svg path,#board .placed[data-renderer] svg line,#board .placed[data-renderer] svg polyline,#board .placed[data-renderer] svg ellipse,#board .placed[data-renderer] svg circle{stroke-width:var(--crochet-line-width)!important;stroke:#111!important;vector-effect:non-scaling-stroke!important}`;document.head.appendChild(s)}
  function apply(){save();stamp();const b=document.getElementById('board');if(b){b.style.setProperty('--crochet-stitch-scale',String(state.sizePct/100));b.style.setProperty('--crochet-line-width',`${Math.max(.05,1.5*state.linePct/100)}px`)}sync()}
  function sync(){for(const[id,val,max]of[['sizeNumberV76',state.sizePct],['sizeSliderV76',state.sizePct,1000],['lineNumberV76',state.linePct],['lineSliderV76',state.linePct,500]]){const e=document.getElementById(id);if(e&&document.activeElement!==e)e.value=max?Math.min(max,val):val}}
  function panel(){const p=document.getElementById('sizingToolsV71');if(!p)return false;let box=document.getElementById('styleControlsV76');if(!box){box=document.createElement('div');box.id='styleControlsV76';box.innerHTML=`<div style="display:grid;grid-template-columns:1fr 86px auto;gap:7px;align-items:center;margin-top:8px"><span>Stitch size</span><input id="sizeNumberV76" type="number" min="1" step="1"><span>%</span><input id="sizeSliderV76" type="range" min="10" max="1000" step="1" style="grid-column:1/-1;width:100%"></div><div style="display:grid;grid-template-columns:1fr 86px auto;gap:7px;align-items:center;margin-top:10px"><span>Line weight</span><input id="lineNumberV76" type="number" min="1" step="1"><span>%</span><input id="lineSliderV76" type="range" min="10" max="500" step="1" style="grid-column:1/-1;width:100%"></div>`;const t=p.querySelector('[data-material-row]');t?p.insertBefore(box,t):p.appendChild(box);const sn=box.querySelector('#sizeNumberV76'),ss=box.querySelector('#sizeSliderV76'),ln=box.querySelector('#lineNumberV76'),ls=box.querySelector('#lineSliderV76');sn.oninput=e=>{if(e.target.value!==''){state.sizePct=positive(e.target.value,state.sizePct);apply()}};ss.oninput=e=>{state.sizePct=positive(e.target.value,state.sizePct);apply()};ln.oninput=e=>{if(e.target.value!==''){state.linePct=positive(e.target.value,state.linePct);apply()}};ls.oninput=e=>{state.linePct=positive(e.target.value,state.linePct);apply()}}apply();return true}
  function refresh(){css();apply();if(!panel())setTimeout(refresh,60)}css();apply();setTimeout(refresh,0);document.addEventListener('click',e=>{if(['laceImport','laceGenerate','photoModeBtn','mobilePhotoModeBtn'].includes(e.target?.id))setTimeout(refresh,0)},true);
})();