// v7.7 — sole owner of stitch size + line weight UI + guide loaders.
(()=>{
  const VERSION='v7.7';
  const KEY='crochetCad.stitchStyleV76';
  let state={sizePct:100,linePct:100};
  try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');if(Number.isFinite(Number(s.sizePct)))state.sizePct=Math.max(1,Math.round(Number(s.sizePct)));if(Number.isFinite(Number(s.linePct)))state.linePct=Math.max(1,Math.round(Number(s.linePct)));}catch{}
  function positive(v,f){const n=Math.round(Number(v));return Number.isFinite(n)&&n>0?n:f;}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{}window.__CROCHET_STITCH_SCALE=state.sizePct/100;window.__CROCHET_PDF_STITCH_SCALE=state.sizePct/100;window.__CROCHET_LINE_WEIGHT_SCALE=state.linePct/100;window.__CROCHET_PDF_LINE_WEIGHT_SCALE=state.linePct/100;}
  function stamp(){window.__CROCHET_CAD_VERSION=VERSION;document.title=`Crochet Pattern Designer · ${VERSION}`;const b=document.querySelector('.brandcopy strong');if(b)b.textContent=`Crochet CAD ${VERSION}`;const p=document.querySelector('#sizingToolsV71 > strong');if(p)p.textContent=`SIZE / GRID · ${VERSION}`;const h=document.querySelector('#photoModeModal .photo-card h2');if(h&&h.textContent.includes('5-PETAL'))h.textContent=`5-PETAL LAYERED LACE FLOWER · ${VERSION}`;}
  function installCss(){if(document.getElementById('stitchPerfV77Style'))return;const s=document.createElement('style');s.id='stitchPerfV77Style';s.textContent=`#board{--crochet-stitch-scale:1;--crochet-line-width:1.5px}#board .placed[data-renderer] svg{transform:scale(var(--crochet-stitch-scale))!important;transform-origin:50% 50%!important;transform-box:fill-box!important;overflow:visible!important;filter:none!important}#board .placed[data-renderer] svg path,#board .placed[data-renderer] svg line,#board .placed[data-renderer] svg polyline,#board .placed[data-renderer] svg ellipse,#board .placed[data-renderer] svg circle{stroke-width:var(--crochet-line-width)!important;stroke:#111!important;vector-effect:non-scaling-stroke!important}`;document.head.appendChild(s);}
  function applyFast(){save();stamp();const board=document.getElementById('board');if(board){board.style.setProperty('--crochet-stitch-scale',String(state.sizePct/100));board.style.setProperty('--crochet-line-width',`${Math.max(.05,1.5*(state.linePct/100))}px`);}syncUI();}
  function syncUI(){const sn=document.getElementById('sizeNumberV76'),ss=document.getElementById('sizeSliderV76'),ln=document.getElementById('lineNumberV76'),ls=document.getElementById('lineSliderV76');if(sn&&document.activeElement!==sn)sn.value=state.sizePct;if(ss)ss.value=Math.min(1000,state.sizePct);if(ln&&document.activeElement!==ln)ln.value=state.linePct;if(ls)ls.value=Math.min(500,state.linePct);}
  function installPanel(){const panel=document.getElementById('sizingToolsV71');if(!panel)return false;let box=document.getElementById('styleControlsV76');if(!box){box=document.createElement('div');box.id='styleControlsV76';box.innerHTML=`<div style="display:grid;grid-template-columns:1fr 86px auto;gap:7px;align-items:center;margin-top:8px"><span>Stitch size</span><input id="sizeNumberV76" type="number" min="1" step="1" value="${state.sizePct}" style="width:86px;text-align:right"><span>%</span><input id="sizeSliderV76" type="range" min="10" max="1000" step="1" value="${Math.min(1000,state.sizePct)}" style="grid-column:1/-1;width:100%"></div><div style="display:grid;grid-template-columns:1fr 86px auto;gap:7px;align-items:center;margin-top:10px"><span>Line weight</span><input id="lineNumberV76" type="number" min="1" step="1" value="${state.linePct}" style="width:86px;text-align:right"><span>%</span><input id="lineSliderV76" type="range" min="10" max="500" step="1" value="${Math.min(500,state.linePct)}" style="grid-column:1/-1;width:100%"></div><div style="font-size:10px;color:#aeb8c0;margin-top:7px">Numeric size is open. Size and line weight are independent. PDF uses the same values.</div>`;const mount=panel.querySelector('#styleControlsMount');if(mount)mount.replaceWith(box);else{const target=panel.querySelector('[data-material-row]');if(target)panel.insertBefore(box,target);else panel.appendChild(box);}const sn=box.querySelector('#sizeNumberV76'),ss=box.querySelector('#sizeSliderV76'),ln=box.querySelector('#lineNumberV76'),ls=box.querySelector('#lineSliderV76');sn.oninput=e=>{if(e.target.value!==''){state.sizePct=positive(e.target.value,state.sizePct);applyFast();}};sn.onchange=sn.onblur=e=>{state.sizePct=positive(e.target.value,state.sizePct);e.target.value=state.sizePct;applyFast();};ss.oninput=e=>{state.sizePct=positive(e.target.value,state.sizePct);applyFast();};ln.oninput=e=>{if(e.target.value!==''){state.linePct=positive(e.target.value,state.linePct);applyFast();}};ln.onchange=ln.onblur=e=>{state.linePct=positive(e.target.value,state.linePct);e.target.value=state.linePct;applyFast();};ls.oninput=e=>{state.linePct=positive(e.target.value,state.linePct);applyFast();};}applyFast();return true;}
  function load(src,id){if(document.getElementById(id))return;const s=document.createElement('script');s.id=id;s.src=src;document.head.appendChild(s);}
  function loadGuides(){load('construction-guides-v7.7.js?v=20260815-1707v77','constructionGuidesLoaderV77');load('guided-pdf-v7.7.js?v=20260815-1707v77','guidedPdfLoaderV77');}
  function refresh(){installCss();applyFast();if(!installPanel())setTimeout(refresh,60);loadGuides();}
  installCss();save();applyFast();setTimeout(refresh,0);document.addEventListener('click',e=>{if(['laceImport','laceGenerate','photoModeBtn','mobilePhotoModeBtn'].includes(e.target?.id))setTimeout(refresh,0)},true);
})();